module Nextbillionai
  module Models
    type access = { lat: Float, lng: Float }

    class Access < Nextbillionai::Internal::Type::BaseModel
      attr_reader lat: Float?

      def lat=: (Float) -> Float

      attr_reader lng: Float?

      def lng=: (Float) -> Float

      def initialize: (?lat: Float, ?lng: Float) -> void

      def to_hash: -> { lat: Float, lng: Float }
    end
  end
end
