module Nextbillionai
  module Models
    type address =
      {
        city: String,
        country_code: String,
        country_name: String,
        county: String,
        district: String,
        house_number: String,
        label: String,
        postal_code: String,
        state: String,
        state_code: String,
        street: String
      }

    class Address < Nextbillionai::Internal::Type::BaseModel
      attr_reader city: String?

      def city=: (String) -> String

      attr_reader country_code: String?

      def country_code=: (String) -> String

      attr_reader country_name: String?

      def country_name=: (String) -> String

      attr_reader county: String?

      def county=: (String) -> String

      attr_reader district: String?

      def district=: (String) -> String

      attr_reader house_number: String?

      def house_number=: (String) -> String

      attr_reader label: String?

      def label=: (String) -> String

      attr_reader postal_code: String?

      def postal_code=: (String) -> String

      attr_reader state: String?

      def state=: (String) -> String

      attr_reader state_code: String?

      def state_code=: (String) -> String

      attr_reader street: String?

      def street=: (String) -> String

      def initialize: (
        ?city: String,
        ?country_code: String,
        ?country_name: String,
        ?county: String,
        ?district: String,
        ?house_number: String,
        ?label: String,
        ?postal_code: String,
        ?state: String,
        ?state_code: String,
        ?street: String
      ) -> void

      def to_hash: -> {
        city: String,
        country_code: String,
        country_name: String,
        county: String,
        district: String,
        house_number: String,
        label: String,
        postal_code: String,
        state: String,
        state_code: String,
        street: String
      }
    end
  end
end
