module Nextbillionai
  module Models
    type batch_create_response =
      { msg: String, status: String, track_id: String }

    class BatchCreateResponse < Nextbillionai::Internal::Type::BaseModel
      attr_reader msg: String?

      def msg=: (String) -> String

      attr_reader status: String?

      def status=: (String) -> String

      attr_reader track_id: String?

      def track_id=: (String) -> String

      def initialize: (?msg: String, ?status: String, ?track_id: String) -> void

      def to_hash: -> { msg: String, status: String, track_id: String }
    end
  end
end
