module Nextbillionai
  module Models
    type direction_compute_route_response =
      {
        msg: String,
        route: Nextbillionai::Models::DirectionComputeRouteResponse::Route,
        status: String
      }

    class DirectionComputeRouteResponse < Nextbillionai::Internal::Type::BaseModel
      attr_reader msg: String?

      def msg=: (String) -> String

      attr_reader route: Nextbillionai::Models::DirectionComputeRouteResponse::Route?

      def route=: (
        Nextbillionai::Models::DirectionComputeRouteResponse::Route
      ) -> Nextbillionai::Models::DirectionComputeRouteResponse::Route

      attr_reader status: String?

      def status=: (String) -> String

      def initialize: (
        ?msg: String,
        ?route: Nextbillionai::Models::DirectionComputeRouteResponse::Route,
        ?status: String
      ) -> void

      def to_hash: -> {
        msg: String,
        route: Nextbillionai::Models::DirectionComputeRouteResponse::Route,
        status: String
      }

      type route =
        {
          distance: Float,
          duration: Float,
          end_location: Nextbillionai::Models::DirectionComputeRouteResponse::Route::EndLocation,
          geojson: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Geojson,
          geometry: String,
          legs: ::Array[Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg],
          start_location: Nextbillionai::Models::DirectionComputeRouteResponse::Route::StartLocation
        }

      class Route < Nextbillionai::Internal::Type::BaseModel
        attr_reader distance: Float?

        def distance=: (Float) -> Float

        attr_reader duration: Float?

        def duration=: (Float) -> Float

        attr_reader end_location: Nextbillionai::Models::DirectionComputeRouteResponse::Route::EndLocation?

        def end_location=: (
          Nextbillionai::Models::DirectionComputeRouteResponse::Route::EndLocation
        ) -> Nextbillionai::Models::DirectionComputeRouteResponse::Route::EndLocation

        attr_reader geojson: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Geojson?

        def geojson=: (
          Nextbillionai::Models::DirectionComputeRouteResponse::Route::Geojson
        ) -> Nextbillionai::Models::DirectionComputeRouteResponse::Route::Geojson

        attr_reader geometry: String?

        def geometry=: (String) -> String

        attr_reader legs: ::Array[Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg]?

        def legs=: (
          ::Array[Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg]
        ) -> ::Array[Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg]

        attr_reader start_location: Nextbillionai::Models::DirectionComputeRouteResponse::Route::StartLocation?

        def start_location=: (
          Nextbillionai::Models::DirectionComputeRouteResponse::Route::StartLocation
        ) -> Nextbillionai::Models::DirectionComputeRouteResponse::Route::StartLocation

        def initialize: (
          ?distance: Float,
          ?duration: Float,
          ?end_location: Nextbillionai::Models::DirectionComputeRouteResponse::Route::EndLocation,
          ?geojson: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Geojson,
          ?geometry: String,
          ?legs: ::Array[Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg],
          ?start_location: Nextbillionai::Models::DirectionComputeRouteResponse::Route::StartLocation
        ) -> void

        def to_hash: -> {
          distance: Float,
          duration: Float,
          end_location: Nextbillionai::Models::DirectionComputeRouteResponse::Route::EndLocation,
          geojson: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Geojson,
          geometry: String,
          legs: ::Array[Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg],
          start_location: Nextbillionai::Models::DirectionComputeRouteResponse::Route::StartLocation
        }

        type end_location = { latitude: Float, longitude: Float }

        class EndLocation < Nextbillionai::Internal::Type::BaseModel
          attr_reader latitude: Float?

          def latitude=: (Float) -> Float

          attr_reader longitude: Float?

          def longitude=: (Float) -> Float

          def initialize: (?latitude: Float, ?longitude: Float) -> void

          def to_hash: -> { latitude: Float, longitude: Float }
        end

        type geojson =
          {
            geometry: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Geojson::Geometry,
            properties: String,
            type: String
          }

        class Geojson < Nextbillionai::Internal::Type::BaseModel
          attr_reader geometry: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Geojson::Geometry?

          def geometry=: (
            Nextbillionai::Models::DirectionComputeRouteResponse::Route::Geojson::Geometry
          ) -> Nextbillionai::Models::DirectionComputeRouteResponse::Route::Geojson::Geometry

          attr_reader properties: String?

          def properties=: (String) -> String

          attr_reader type: String?

          def type=: (String) -> String

          def initialize: (
            ?geometry: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Geojson::Geometry,
            ?properties: String,
            ?type: String
          ) -> void

          def to_hash: -> {
            geometry: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Geojson::Geometry,
            properties: String,
            type: String
          }

          type geometry = { coordinates: ::Array[Float], type: String }

          class Geometry < Nextbillionai::Internal::Type::BaseModel
            attr_reader coordinates: ::Array[Float]?

            def coordinates=: (::Array[Float]) -> ::Array[Float]

            attr_reader type: String?

            def type=: (String) -> String

            def initialize: (
              ?coordinates: ::Array[Float],
              ?type: String
            ) -> void

            def to_hash: -> { coordinates: ::Array[Float], type: String }
          end
        end

        type leg =
          {
            distance: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Distance,
            duration: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Duration,
            end_location: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::EndLocation,
            start_location: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::StartLocation,
            steps: ::Array[Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step]
          }

        class Leg < Nextbillionai::Internal::Type::BaseModel
          attr_reader distance: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Distance?

          def distance=: (
            Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Distance
          ) -> Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Distance

          attr_reader duration: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Duration?

          def duration=: (
            Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Duration
          ) -> Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Duration

          attr_reader end_location: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::EndLocation?

          def end_location=: (
            Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::EndLocation
          ) -> Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::EndLocation

          attr_reader start_location: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::StartLocation?

          def start_location=: (
            Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::StartLocation
          ) -> Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::StartLocation

          attr_reader steps: ::Array[Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step]?

          def steps=: (
            ::Array[Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step]
          ) -> ::Array[Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step]

          def initialize: (
            ?distance: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Distance,
            ?duration: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Duration,
            ?end_location: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::EndLocation,
            ?start_location: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::StartLocation,
            ?steps: ::Array[Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step]
          ) -> void

          def to_hash: -> {
            distance: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Distance,
            duration: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Duration,
            end_location: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::EndLocation,
            start_location: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::StartLocation,
            steps: ::Array[Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step]
          }

          type distance = { value: Float }

          class Distance < Nextbillionai::Internal::Type::BaseModel
            attr_reader value: Float?

            def value=: (Float) -> Float

            def initialize: (?value: Float) -> void

            def to_hash: -> { value: Float }
          end

          type duration = { value: Float }

          class Duration < Nextbillionai::Internal::Type::BaseModel
            attr_reader value: Float?

            def value=: (Float) -> Float

            def initialize: (?value: Float) -> void

            def to_hash: -> { value: Float }
          end

          type end_location = { latitude: Float, longitude: Float }

          class EndLocation < Nextbillionai::Internal::Type::BaseModel
            attr_reader latitude: Float?

            def latitude=: (Float) -> Float

            attr_reader longitude: Float?

            def longitude=: (Float) -> Float

            def initialize: (?latitude: Float, ?longitude: Float) -> void

            def to_hash: -> { latitude: Float, longitude: Float }
          end

          type start_location = { latitude: Float, longitude: Float }

          class StartLocation < Nextbillionai::Internal::Type::BaseModel
            attr_reader latitude: Float?

            def latitude=: (Float) -> Float

            attr_reader longitude: Float?

            def longitude=: (Float) -> Float

            def initialize: (?latitude: Float, ?longitude: Float) -> void

            def to_hash: -> { latitude: Float, longitude: Float }
          end

          type step =
            {
              distance: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::Distance,
              duration: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::Duration,
              end_location: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::EndLocation,
              geojson: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::Geojson,
              geometry: String,
              maneuver: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::Maneuver,
              start_location: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::StartLocation
            }

          class Step < Nextbillionai::Internal::Type::BaseModel
            attr_reader distance: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::Distance?

            def distance=: (
              Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::Distance
            ) -> Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::Distance

            attr_reader duration: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::Duration?

            def duration=: (
              Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::Duration
            ) -> Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::Duration

            attr_reader end_location: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::EndLocation?

            def end_location=: (
              Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::EndLocation
            ) -> Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::EndLocation

            attr_reader geojson: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::Geojson?

            def geojson=: (
              Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::Geojson
            ) -> Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::Geojson

            attr_reader geometry: String?

            def geometry=: (String) -> String

            attr_reader maneuver: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::Maneuver?

            def maneuver=: (
              Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::Maneuver
            ) -> Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::Maneuver

            attr_reader start_location: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::StartLocation?

            def start_location=: (
              Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::StartLocation
            ) -> Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::StartLocation

            def initialize: (
              ?distance: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::Distance,
              ?duration: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::Duration,
              ?end_location: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::EndLocation,
              ?geojson: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::Geojson,
              ?geometry: String,
              ?maneuver: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::Maneuver,
              ?start_location: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::StartLocation
            ) -> void

            def to_hash: -> {
              distance: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::Distance,
              duration: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::Duration,
              end_location: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::EndLocation,
              geojson: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::Geojson,
              geometry: String,
              maneuver: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::Maneuver,
              start_location: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::StartLocation
            }

            type distance = { value: Float }

            class Distance < Nextbillionai::Internal::Type::BaseModel
              attr_reader value: Float?

              def value=: (Float) -> Float

              def initialize: (?value: Float) -> void

              def to_hash: -> { value: Float }
            end

            type duration = { value: Float }

            class Duration < Nextbillionai::Internal::Type::BaseModel
              attr_reader value: Float?

              def value=: (Float) -> Float

              def initialize: (?value: Float) -> void

              def to_hash: -> { value: Float }
            end

            type end_location = { latitude: Float, longitude: Float }

            class EndLocation < Nextbillionai::Internal::Type::BaseModel
              attr_reader latitude: Float?

              def latitude=: (Float) -> Float

              attr_reader longitude: Float?

              def longitude=: (Float) -> Float

              def initialize: (?latitude: Float, ?longitude: Float) -> void

              def to_hash: -> { latitude: Float, longitude: Float }
            end

            type geojson =
              {
                geometry: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::Geojson::Geometry,
                properties: String,
                type: String
              }

            class Geojson < Nextbillionai::Internal::Type::BaseModel
              attr_reader geometry: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::Geojson::Geometry?

              def geometry=: (
                Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::Geojson::Geometry
              ) -> Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::Geojson::Geometry

              attr_reader properties: String?

              def properties=: (String) -> String

              attr_reader type: String?

              def type=: (String) -> String

              def initialize: (
                ?geometry: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::Geojson::Geometry,
                ?properties: String,
                ?type: String
              ) -> void

              def to_hash: -> {
                geometry: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::Geojson::Geometry,
                properties: String,
                type: String
              }

              type geometry = { coordinates: ::Array[Float], type: String }

              class Geometry < Nextbillionai::Internal::Type::BaseModel
                attr_reader coordinates: ::Array[Float]?

                def coordinates=: (::Array[Float]) -> ::Array[Float]

                attr_reader type: String?

                def type=: (String) -> String

                def initialize: (
                  ?coordinates: ::Array[Float],
                  ?type: String
                ) -> void

                def to_hash: -> { coordinates: ::Array[Float], type: String }
              end
            end

            type maneuver =
              {
                bearing_after: Integer,
                bearing_before: Integer,
                coordinate: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::Maneuver::Coordinate,
                maneuver_type: String,
                modifier: String
              }

            class Maneuver < Nextbillionai::Internal::Type::BaseModel
              attr_reader bearing_after: Integer?

              def bearing_after=: (Integer) -> Integer

              attr_reader bearing_before: Integer?

              def bearing_before=: (Integer) -> Integer

              attr_reader coordinate: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::Maneuver::Coordinate?

              def coordinate=: (
                Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::Maneuver::Coordinate
              ) -> Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::Maneuver::Coordinate

              attr_reader maneuver_type: String?

              def maneuver_type=: (String) -> String

              attr_reader modifier: String?

              def modifier=: (String) -> String

              def initialize: (
                ?bearing_after: Integer,
                ?bearing_before: Integer,
                ?coordinate: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::Maneuver::Coordinate,
                ?maneuver_type: String,
                ?modifier: String
              ) -> void

              def to_hash: -> {
                bearing_after: Integer,
                bearing_before: Integer,
                coordinate: Nextbillionai::Models::DirectionComputeRouteResponse::Route::Leg::Step::Maneuver::Coordinate,
                maneuver_type: String,
                modifier: String
              }

              type coordinate = { latitude: Float, longitude: Float }

              class Coordinate < Nextbillionai::Internal::Type::BaseModel
                attr_reader latitude: Float?

                def latitude=: (Float) -> Float

                attr_reader longitude: Float?

                def longitude=: (Float) -> Float

                def initialize: (?latitude: Float, ?longitude: Float) -> void

                def to_hash: -> { latitude: Float, longitude: Float }
              end
            end

            type start_location = { latitude: Float, longitude: Float }

            class StartLocation < Nextbillionai::Internal::Type::BaseModel
              attr_reader latitude: Float?

              def latitude=: (Float) -> Float

              attr_reader longitude: Float?

              def longitude=: (Float) -> Float

              def initialize: (?latitude: Float, ?longitude: Float) -> void

              def to_hash: -> { latitude: Float, longitude: Float }
            end
          end
        end

        type start_location = { latitude: Float, longitude: Float }

        class StartLocation < Nextbillionai::Internal::Type::BaseModel
          attr_reader latitude: Float?

          def latitude=: (Float) -> Float

          attr_reader longitude: Float?

          def longitude=: (Float) -> Float

          def initialize: (?latitude: Float, ?longitude: Float) -> void

          def to_hash: -> { latitude: Float, longitude: Float }
        end
      end
    end
  end
end
