module Nextbillionai
  module Models
    type geofence_contains_response =
      {
        data: Nextbillionai::Models::GeofenceContainsResponse::Data,
        status: String
      }

    class GeofenceContainsResponse < Nextbillionai::Internal::Type::BaseModel
      attr_reader data: Nextbillionai::Models::GeofenceContainsResponse::Data?

      def data=: (
        Nextbillionai::Models::GeofenceContainsResponse::Data
      ) -> Nextbillionai::Models::GeofenceContainsResponse::Data

      attr_reader status: String?

      def status=: (String) -> String

      def initialize: (
        ?data: Nextbillionai::Models::GeofenceContainsResponse::Data,
        ?status: String
      ) -> void

      def to_hash: -> {
        data: Nextbillionai::Models::GeofenceContainsResponse::Data,
        status: String
      }

      type data =
        {
          result_list: ::Array[Nextbillionai::Models::GeofenceContainsResponse::Data::ResultList]
        }

      class Data < Nextbillionai::Internal::Type::BaseModel
        attr_reader result_list: ::Array[Nextbillionai::Models::GeofenceContainsResponse::Data::ResultList]?

        def result_list=: (
          ::Array[Nextbillionai::Models::GeofenceContainsResponse::Data::ResultList]
        ) -> ::Array[Nextbillionai::Models::GeofenceContainsResponse::Data::ResultList]

        def initialize: (
          ?result_list: ::Array[Nextbillionai::Models::GeofenceContainsResponse::Data::ResultList]
        ) -> void

        def to_hash: -> {
          result_list: ::Array[Nextbillionai::Models::GeofenceContainsResponse::Data::ResultList]
        }

        type result_list =
          {
            geofence_detail: Nextbillionai::GeofenceAPI,
            geofence_id: String,
            result: ::Array[Nextbillionai::Models::GeofenceContainsResponse::Data::ResultList::Result]
          }

        class ResultList < Nextbillionai::Internal::Type::BaseModel
          attr_reader geofence_detail: Nextbillionai::GeofenceAPI?

          def geofence_detail=: (
            Nextbillionai::GeofenceAPI
          ) -> Nextbillionai::GeofenceAPI

          attr_reader geofence_id: String?

          def geofence_id=: (String) -> String

          attr_reader result: ::Array[Nextbillionai::Models::GeofenceContainsResponse::Data::ResultList::Result]?

          def result=: (
            ::Array[Nextbillionai::Models::GeofenceContainsResponse::Data::ResultList::Result]
          ) -> ::Array[Nextbillionai::Models::GeofenceContainsResponse::Data::ResultList::Result]

          def initialize: (
            ?geofence_detail: Nextbillionai::GeofenceAPI,
            ?geofence_id: String,
            ?result: ::Array[Nextbillionai::Models::GeofenceContainsResponse::Data::ResultList::Result]
          ) -> void

          def to_hash: -> {
            geofence_detail: Nextbillionai::GeofenceAPI,
            geofence_id: String,
            result: ::Array[Nextbillionai::Models::GeofenceContainsResponse::Data::ResultList::Result]
          }

          type result = { contain: bool, location_index: Integer }

          class Result < Nextbillionai::Internal::Type::BaseModel
            attr_reader contain: bool?

            def contain=: (bool) -> bool

            attr_reader location_index: Integer?

            def location_index=: (Integer) -> Integer

            def initialize: (?contain: bool, ?location_index: Integer) -> void

            def to_hash: -> { contain: bool, location_index: Integer }
          end
        end
      end
    end
  end
end
