module Nextbillionai
  module Models
    type lookup_by_id_response =
      { items: ::Array[Nextbillionai::Models::LookupByIDResponse::Item] }

    class LookupByIDResponse < Nextbillionai::Internal::Type::BaseModel
      attr_reader items: ::Array[Nextbillionai::Models::LookupByIDResponse::Item]?

      def items=: (
        ::Array[Nextbillionai::Models::LookupByIDResponse::Item]
      ) -> ::Array[Nextbillionai::Models::LookupByIDResponse::Item]

      def initialize: (
        ?items: ::Array[Nextbillionai::Models::LookupByIDResponse::Item]
      ) -> void

      def to_hash: -> {
        items: ::Array[Nextbillionai::Models::LookupByIDResponse::Item]
      }

      type item =
        {
          id: String,
          access: Nextbillionai::Access,
          address: Nextbillionai::Address,
          categories: ::Array[Nextbillionai::Categories],
          contacts: ::Array[Nextbillionai::Contacts],
          map_view: Nextbillionai::MapView,
          position: Nextbillionai::Position,
          title: String
        }

      class Item < Nextbillionai::Internal::Type::BaseModel
        attr_reader id: String?

        def id=: (String) -> String

        attr_reader access: Nextbillionai::Access?

        def access=: (Nextbillionai::Access) -> Nextbillionai::Access

        attr_reader address: Nextbillionai::Address?

        def address=: (Nextbillionai::Address) -> Nextbillionai::Address

        attr_reader categories: ::Array[Nextbillionai::Categories]?

        def categories=: (
          ::Array[Nextbillionai::Categories]
        ) -> ::Array[Nextbillionai::Categories]

        attr_reader contacts: ::Array[Nextbillionai::Contacts]?

        def contacts=: (
          ::Array[Nextbillionai::Contacts]
        ) -> ::Array[Nextbillionai::Contacts]

        attr_reader map_view: Nextbillionai::MapView?

        def map_view=: (Nextbillionai::MapView) -> Nextbillionai::MapView

        attr_reader position: Nextbillionai::Position?

        def position=: (Nextbillionai::Position) -> Nextbillionai::Position

        attr_reader title: String?

        def title=: (String) -> String

        def initialize: (
          ?id: String,
          ?access: Nextbillionai::Access,
          ?address: Nextbillionai::Address,
          ?categories: ::Array[Nextbillionai::Categories],
          ?contacts: ::Array[Nextbillionai::Contacts],
          ?map_view: Nextbillionai::MapView,
          ?position: Nextbillionai::Position,
          ?title: String
        ) -> void

        def to_hash: -> {
          id: String,
          access: Nextbillionai::Access,
          address: Nextbillionai::Address,
          categories: ::Array[Nextbillionai::Categories],
          contacts: ::Array[Nextbillionai::Contacts],
          map_view: Nextbillionai::MapView,
          position: Nextbillionai::Position,
          title: String
        }
      end
    end
  end
end
