module Nextbillionai
  module Models
    type map_create_segment_params =
      {  } & Nextbillionai::Internal::Type::request_parameters

    class MapCreateSegmentParams < Nextbillionai::Internal::Type::BaseModel
      extend Nextbillionai::Internal::Type::RequestParameters::Converter
      include Nextbillionai::Internal::Type::RequestParameters

      def initialize: (?request_options: Nextbillionai::request_opts) -> void

      def to_hash: -> { request_options: Nextbillionai::RequestOptions }
    end
  end
end
