module Nextbillionai
  module Models
    type map_view = { east: String, north: String, south: String, west: String }

    class MapView < Nextbillionai::Internal::Type::BaseModel
      attr_reader east: String?

      def east=: (String) -> String

      attr_reader north: String?

      def north=: (String) -> String

      attr_reader south: String?

      def south=: (String) -> String

      attr_reader west: String?

      def west=: (String) -> String

      def initialize: (
        ?east: String,
        ?north: String,
        ?south: String,
        ?west: String
      ) -> void

      def to_hash: -> {
        east: String,
        north: String,
        south: String,
        west: String
      }
    end
  end
end
