module Nextbillionai
  module Models
    type mdm_create_distance_matrix_response =
      {
        code: String,
        message: String,
        task_id: String,
        warning: ::Array[String]
      }

    class MdmCreateDistanceMatrixResponse < Nextbillionai::Internal::Type::BaseModel
      attr_reader code: String?

      def code=: (String) -> String

      attr_reader message: String?

      def message=: (String) -> String

      attr_reader task_id: String?

      def task_id=: (String) -> String

      attr_reader warning: ::Array[String]?

      def warning=: (::Array[String]) -> ::Array[String]

      def initialize: (
        ?code: String,
        ?message: String,
        ?task_id: String,
        ?warning: ::Array[String]
      ) -> void

      def to_hash: -> {
        code: String,
        message: String,
        task_id: String,
        warning: ::Array[String]
      }
    end
  end
end
