module Nextbillionai
  module Models
    type multigeocode_search_params =
      {
        key: String,
        at: Nextbillionai::MultigeocodeSearchParams::At,
        query: String,
        city: String,
        country: String,
        district: String,
        limit: Integer,
        radius: String,
        state: String,
        street: String,
        sub_district: String
      }
      & Nextbillionai::Internal::Type::request_parameters

    class MultigeocodeSearchParams < Nextbillionai::Internal::Type::BaseModel
      extend Nextbillionai::Internal::Type::RequestParameters::Converter
      include Nextbillionai::Internal::Type::RequestParameters

      attr_accessor key: String

      attr_accessor at: Nextbillionai::MultigeocodeSearchParams::At

      attr_accessor query: String

      attr_reader city: String?

      def city=: (String) -> String

      attr_reader country: String?

      def country=: (String) -> String

      attr_reader district: String?

      def district=: (String) -> String

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_reader radius: String?

      def radius=: (String) -> String

      attr_reader state: String?

      def state=: (String) -> String

      attr_reader street: String?

      def street=: (String) -> String

      attr_reader sub_district: String?

      def sub_district=: (String) -> String

      def initialize: (
        key: String,
        at: Nextbillionai::MultigeocodeSearchParams::At,
        query: String,
        ?city: String,
        ?country: String,
        ?district: String,
        ?limit: Integer,
        ?radius: String,
        ?state: String,
        ?street: String,
        ?sub_district: String,
        ?request_options: Nextbillionai::request_opts
      ) -> void

      def to_hash: -> {
        key: String,
        at: Nextbillionai::MultigeocodeSearchParams::At,
        query: String,
        city: String,
        country: String,
        district: String,
        limit: Integer,
        radius: String,
        state: String,
        street: String,
        sub_district: String,
        request_options: Nextbillionai::RequestOptions
      }

      type at = { lat: Float, lng: Float }

      class At < Nextbillionai::Internal::Type::BaseModel
        attr_accessor lat: Float

        attr_accessor lng: Float

        def initialize: (lat: Float, lng: Float) -> void

        def to_hash: -> { lat: Float, lng: Float }
      end
    end
  end
end
