module Nextbillionai
  module Models
    type revgeocode_retrieve_params =
      { at: String, key: String, in_: String, lang: String }
      & Nextbillionai::Internal::Type::request_parameters

    class RevgeocodeRetrieveParams < Nextbillionai::Internal::Type::BaseModel
      extend Nextbillionai::Internal::Type::RequestParameters::Converter
      include Nextbillionai::Internal::Type::RequestParameters

      attr_accessor at: String

      attr_accessor key: String

      attr_reader in_: String?

      def in_=: (String) -> String

      attr_reader lang: String?

      def lang=: (String) -> String

      def initialize: (
        at: String,
        key: String,
        ?in_: String,
        ?lang: String,
        ?request_options: Nextbillionai::request_opts
      ) -> void

      def to_hash: -> {
        at: String,
        key: String,
        in_: String,
        lang: String,
        request_options: Nextbillionai::RequestOptions
      }
    end
  end
end
