module Nextbillionai
  module Models
    type snap_to_road_snap_response =
      {
        distance: Integer,
        geojson: Nextbillionai::Models::SnapToRoadSnapResponse::Geojson,
        geometry: ::Array[String],
        msg: String,
        road_info: Nextbillionai::Models::SnapToRoadSnapResponse::RoadInfo,
        snapped_points: ::Array[Nextbillionai::Models::SnapToRoadSnapResponse::SnappedPoint],
        status: String
      }

    class SnapToRoadSnapResponse < Nextbillionai::Internal::Type::BaseModel
      attr_reader distance: Integer?

      def distance=: (Integer) -> Integer

      attr_reader geojson: Nextbillionai::Models::SnapToRoadSnapResponse::Geojson?

      def geojson=: (
        Nextbillionai::Models::SnapToRoadSnapResponse::Geojson
      ) -> Nextbillionai::Models::SnapToRoadSnapResponse::Geojson

      attr_reader geometry: ::Array[String]?

      def geometry=: (::Array[String]) -> ::Array[String]

      attr_reader msg: String?

      def msg=: (String) -> String

      attr_reader road_info: Nextbillionai::Models::SnapToRoadSnapResponse::RoadInfo?

      def road_info=: (
        Nextbillionai::Models::SnapToRoadSnapResponse::RoadInfo
      ) -> Nextbillionai::Models::SnapToRoadSnapResponse::RoadInfo

      attr_reader snapped_points: ::Array[Nextbillionai::Models::SnapToRoadSnapResponse::SnappedPoint]?

      def snapped_points=: (
        ::Array[Nextbillionai::Models::SnapToRoadSnapResponse::SnappedPoint]
      ) -> ::Array[Nextbillionai::Models::SnapToRoadSnapResponse::SnappedPoint]

      attr_reader status: String?

      def status=: (String) -> String

      def initialize: (
        ?distance: Integer,
        ?geojson: Nextbillionai::Models::SnapToRoadSnapResponse::Geojson,
        ?geometry: ::Array[String],
        ?msg: String,
        ?road_info: Nextbillionai::Models::SnapToRoadSnapResponse::RoadInfo,
        ?snapped_points: ::Array[Nextbillionai::Models::SnapToRoadSnapResponse::SnappedPoint],
        ?status: String
      ) -> void

      def to_hash: -> {
        distance: Integer,
        geojson: Nextbillionai::Models::SnapToRoadSnapResponse::Geojson,
        geometry: ::Array[String],
        msg: String,
        road_info: Nextbillionai::Models::SnapToRoadSnapResponse::RoadInfo,
        snapped_points: ::Array[Nextbillionai::Models::SnapToRoadSnapResponse::SnappedPoint],
        status: String
      }

      type geojson =
        {
          geometry: Nextbillionai::Models::SnapToRoadSnapResponse::Geojson::Geometry,
          properties: String,
          type: String
        }

      class Geojson < Nextbillionai::Internal::Type::BaseModel
        attr_reader geometry: Nextbillionai::Models::SnapToRoadSnapResponse::Geojson::Geometry?

        def geometry=: (
          Nextbillionai::Models::SnapToRoadSnapResponse::Geojson::Geometry
        ) -> Nextbillionai::Models::SnapToRoadSnapResponse::Geojson::Geometry

        attr_reader properties: String?

        def properties=: (String) -> String

        attr_reader type: String?

        def type=: (String) -> String

        def initialize: (
          ?geometry: Nextbillionai::Models::SnapToRoadSnapResponse::Geojson::Geometry,
          ?properties: String,
          ?type: String
        ) -> void

        def to_hash: -> {
          geometry: Nextbillionai::Models::SnapToRoadSnapResponse::Geojson::Geometry,
          properties: String,
          type: String
        }

        type geometry = { coordinates: ::Array[Float], type: String }

        class Geometry < Nextbillionai::Internal::Type::BaseModel
          attr_reader coordinates: ::Array[Float]?

          def coordinates=: (::Array[Float]) -> ::Array[Float]

          attr_reader type: String?

          def type=: (String) -> String

          def initialize: (?coordinates: ::Array[Float], ?type: String) -> void

          def to_hash: -> { coordinates: ::Array[Float], type: String }
        end
      end

      type road_info =
        {
          max_speed: ::Array[Nextbillionai::Models::SnapToRoadSnapResponse::RoadInfo::MaxSpeed]
        }

      class RoadInfo < Nextbillionai::Internal::Type::BaseModel
        attr_reader max_speed: ::Array[Nextbillionai::Models::SnapToRoadSnapResponse::RoadInfo::MaxSpeed]?

        def max_speed=: (
          ::Array[Nextbillionai::Models::SnapToRoadSnapResponse::RoadInfo::MaxSpeed]
        ) -> ::Array[Nextbillionai::Models::SnapToRoadSnapResponse::RoadInfo::MaxSpeed]

        def initialize: (
          ?max_speed: ::Array[Nextbillionai::Models::SnapToRoadSnapResponse::RoadInfo::MaxSpeed]
        ) -> void

        def to_hash: -> {
          max_speed: ::Array[Nextbillionai::Models::SnapToRoadSnapResponse::RoadInfo::MaxSpeed]
        }

        type max_speed = { length: Integer, offset: Integer, value: Float }

        class MaxSpeed < Nextbillionai::Internal::Type::BaseModel
          attr_reader length: Integer?

          def length=: (Integer) -> Integer

          attr_reader offset: Integer?

          def offset=: (Integer) -> Integer

          attr_reader value: Float?

          def value=: (Float) -> Float

          def initialize: (
            ?length: Integer,
            ?offset: Integer,
            ?value: Float
          ) -> void

          def to_hash: -> { length: Integer, offset: Integer, value: Float }
        end
      end

      type snapped_point =
        {
          bearing: Float,
          distance: Float,
          location: Nextbillionai::Models::SnapToRoadSnapResponse::SnappedPoint::Location,
          name: String,
          original_index: Integer
        }

      class SnappedPoint < Nextbillionai::Internal::Type::BaseModel
        attr_accessor bearing: Float

        attr_accessor distance: Float

        attr_accessor location: Nextbillionai::Models::SnapToRoadSnapResponse::SnappedPoint::Location

        attr_accessor name: String

        attr_accessor original_index: Integer

        def initialize: (
          bearing: Float,
          distance: Float,
          location: Nextbillionai::Models::SnapToRoadSnapResponse::SnappedPoint::Location,
          name: String,
          original_index: Integer
        ) -> void

        def to_hash: -> {
          bearing: Float,
          distance: Float,
          location: Nextbillionai::Models::SnapToRoadSnapResponse::SnappedPoint::Location,
          name: String,
          original_index: Integer
        }

        type location = { latitude: Float, longitude: Float }

        class Location < Nextbillionai::Internal::Type::BaseModel
          attr_accessor latitude: Float

          attr_accessor longitude: Float

          def initialize: (latitude: Float, longitude: Float) -> void

          def to_hash: -> { latitude: Float, longitude: Float }
        end
      end
    end
  end
end
