module NextbillionSDK
  module Models
    module DistanceMatrix
      type json_create_params =
        {  } & NextbillionSDK::Internal::Type::request_parameters

      class JsonCreateParams < NextbillionSDK::Internal::Type::BaseModel
        extend NextbillionSDK::Internal::Type::RequestParameters::Converter
        include NextbillionSDK::Internal::Type::RequestParameters

        def initialize: (?request_options: NextbillionSDK::request_opts) -> void

        def to_hash: -> { request_options: NextbillionSDK::RequestOptions }
      end
    end
  end
end
