module Nextbillionai
  module Models
    module Fleetify
      module RouteStepCompletionMode = Routes::RouteStepCompletionMode

      module Routes
        type route_step_completion_mode =
          :"`manual`" | :"`geofence`" | :"`geofence_manual_fallback`"

        module RouteStepCompletionMode
          extend Nextbillionai::Internal::Type::Enum

          MANUAL: :"`manual`"
          GEOFENCE: :"`geofence`"
          GEOFENCE_MANUAL_FALLBACK: :"`geofence_manual_fallback`"

          def self?.values: -> ::Array[Nextbillionai::Models::Fleetify::Routes::route_step_completion_mode]
        end
      end
    end
  end
end
