module Nextbillionai
  module Models
    module Fleetify
      module Routes
        type step_complete_params =
          {
            route_id: String,
            key: String,
            document: top,
            mode: String,
            status: String
          }
          & Nextbillionai::Internal::Type::request_parameters

        class StepCompleteParams < Nextbillionai::Internal::Type::BaseModel
          extend Nextbillionai::Internal::Type::RequestParameters::Converter
          include Nextbillionai::Internal::Type::RequestParameters

          attr_accessor route_id: String

          attr_accessor key: String

          attr_reader document: top?

          def document=: (top) -> top

          attr_reader mode: String?

          def mode=: (String) -> String

          attr_reader status: String?

          def status=: (String) -> String

          def initialize: (
            route_id: String,
            key: String,
            ?document: top,
            ?mode: String,
            ?status: String,
            ?request_options: Nextbillionai::request_opts
          ) -> void

          def to_hash: -> {
            route_id: String,
            key: String,
            document: top,
            mode: String,
            status: String,
            request_options: Nextbillionai::RequestOptions
          }
        end
      end
    end
  end
end
