module Nextbillionai
  module Models
    module Fleetify
      module Routes
        type step_create_response =
          {
            data: Nextbillionai::Fleetify::Routes::RouteStepsResponse,
            message: String,
            status: Integer
          }

        class StepCreateResponse < Nextbillionai::Internal::Type::BaseModel
          attr_reader data: Nextbillionai::Fleetify::Routes::RouteStepsResponse?

          def data=: (
            Nextbillionai::Fleetify::Routes::RouteStepsResponse
          ) -> Nextbillionai::Fleetify::Routes::RouteStepsResponse

          attr_reader message: String?

          def message=: (String) -> String

          attr_reader status: Integer?

          def status=: (Integer) -> Integer

          def initialize: (
            ?data: Nextbillionai::Fleetify::Routes::RouteStepsResponse,
            ?message: String,
            ?status: Integer
          ) -> void

          def to_hash: -> {
            data: Nextbillionai::Fleetify::Routes::RouteStepsResponse,
            message: String,
            status: Integer
          }
        end
      end
    end
  end
end
