module NextbillionSDK
  module Models
    module Fleetify
      module Routes
        type step_delete_params =
          { route_id: String, key: String }
          & NextbillionSDK::Internal::Type::request_parameters

        class StepDeleteParams < NextbillionSDK::Internal::Type::BaseModel
          extend NextbillionSDK::Internal::Type::RequestParameters::Converter
          include NextbillionSDK::Internal::Type::RequestParameters

          attr_accessor route_id: String

          attr_accessor key: String

          def initialize: (
            route_id: String,
            key: String,
            ?request_options: NextbillionSDK::request_opts
          ) -> void

          def to_hash: -> {
            route_id: String,
            key: String,
            request_options: NextbillionSDK::RequestOptions
          }
        end
      end
    end
  end
end
