module NextbillionSDK
  module Resources
    class Geofence
      class Console
        def preview: (
          type: NextbillionSDK::Models::GeofenceEntityCreate::type_,
          ?circle: NextbillionSDK::GeofenceEntityCreate::Circle,
          ?custom_id: String,
          ?isochrone: NextbillionSDK::GeofenceEntityCreate::Isochrone,
          ?meta_data: top,
          ?name: String,
          ?polygon: NextbillionSDK::GeofenceEntityCreate::Polygon,
          ?tags: ::Array[String],
          ?request_options: NextbillionSDK::request_opts
        ) -> NextbillionSDK::Models::Geofence::ConsolePreviewResponse

        def search: (
          query: String,
          ?request_options: NextbillionSDK::request_opts
        ) -> NextbillionSDK::Models::Geofence::ConsoleSearchResponse

        def initialize: (client: NextbillionSDK::Client) -> void
      end
    end
  end
end
