module NextbillionSDK
  module Models
    module Skynet
      module Search
        type polygon_create_params =
          {
            key: String,
            polygon: NextbillionSDK::Skynet::Search::PolygonCreateParams::Polygon,
            filter: String,
            match_filter: NextbillionSDK::Skynet::Search::PolygonCreateParams::MatchFilter,
            max_search_limit: bool,
            pn: Integer,
            ps: Integer,
            sort: NextbillionSDK::Skynet::Search::PolygonCreateParams::Sort
          }
          & NextbillionSDK::Internal::Type::request_parameters

        class PolygonCreateParams < NextbillionSDK::Internal::Type::BaseModel
          extend NextbillionSDK::Internal::Type::RequestParameters::Converter
          include NextbillionSDK::Internal::Type::RequestParameters

          attr_accessor key: String

          attr_accessor polygon: NextbillionSDK::Skynet::Search::PolygonCreateParams::Polygon

          attr_reader filter: String?

          def filter=: (String) -> String

          attr_reader match_filter: NextbillionSDK::Skynet::Search::PolygonCreateParams::MatchFilter?

          def match_filter=: (
            NextbillionSDK::Skynet::Search::PolygonCreateParams::MatchFilter
          ) -> NextbillionSDK::Skynet::Search::PolygonCreateParams::MatchFilter

          attr_reader max_search_limit: bool?

          def max_search_limit=: (bool) -> bool

          attr_reader pn: Integer?

          def pn=: (Integer) -> Integer

          attr_reader ps: Integer?

          def ps=: (Integer) -> Integer

          attr_reader sort: NextbillionSDK::Skynet::Search::PolygonCreateParams::Sort?

          def sort=: (
            NextbillionSDK::Skynet::Search::PolygonCreateParams::Sort
          ) -> NextbillionSDK::Skynet::Search::PolygonCreateParams::Sort

          def initialize: (
            key: String,
            polygon: NextbillionSDK::Skynet::Search::PolygonCreateParams::Polygon,
            ?filter: String,
            ?match_filter: NextbillionSDK::Skynet::Search::PolygonCreateParams::MatchFilter,
            ?max_search_limit: bool,
            ?pn: Integer,
            ?ps: Integer,
            ?sort: NextbillionSDK::Skynet::Search::PolygonCreateParams::Sort,
            ?request_options: NextbillionSDK::request_opts
          ) -> void

          def to_hash: -> {
            key: String,
            polygon: NextbillionSDK::Skynet::Search::PolygonCreateParams::Polygon,
            filter: String,
            match_filter: NextbillionSDK::Skynet::Search::PolygonCreateParams::MatchFilter,
            max_search_limit: bool,
            pn: Integer,
            ps: Integer,
            sort: NextbillionSDK::Skynet::Search::PolygonCreateParams::Sort,
            request_options: NextbillionSDK::RequestOptions
          }

          type polygon = { coordinates: ::Array[Float], type: String }

          class Polygon < NextbillionSDK::Internal::Type::BaseModel
            attr_accessor coordinates: ::Array[Float]

            attr_accessor type: String

            def initialize: (coordinates: ::Array[Float], type: String) -> void

            def to_hash: -> { coordinates: ::Array[Float], type: String }
          end

          type match_filter =
            {
              include_all_of_attributes: String,
              include_any_of_attributes: String
            }

          class MatchFilter < NextbillionSDK::Internal::Type::BaseModel
            attr_reader include_all_of_attributes: String?

            def include_all_of_attributes=: (String) -> String

            attr_reader include_any_of_attributes: String?

            def include_any_of_attributes=: (String) -> String

            def initialize: (
              ?include_all_of_attributes: String,
              ?include_any_of_attributes: String
            ) -> void

            def to_hash: -> {
              include_all_of_attributes: String,
              include_any_of_attributes: String
            }
          end

          type sort =
            {
              sort_by: NextbillionSDK::Models::Skynet::Search::PolygonCreateParams::Sort::sort_by,
              sort_destination: NextbillionSDK::Skynet::Search::PolygonCreateParams::Sort::SortDestination,
              sort_driving_mode: NextbillionSDK::Models::Skynet::Search::PolygonCreateParams::Sort::sort_driving_mode
            }

          class Sort < NextbillionSDK::Internal::Type::BaseModel
            attr_reader sort_by: NextbillionSDK::Models::Skynet::Search::PolygonCreateParams::Sort::sort_by?

            def sort_by=: (
              NextbillionSDK::Models::Skynet::Search::PolygonCreateParams::Sort::sort_by
            ) -> NextbillionSDK::Models::Skynet::Search::PolygonCreateParams::Sort::sort_by

            attr_reader sort_destination: NextbillionSDK::Skynet::Search::PolygonCreateParams::Sort::SortDestination?

            def sort_destination=: (
              NextbillionSDK::Skynet::Search::PolygonCreateParams::Sort::SortDestination
            ) -> NextbillionSDK::Skynet::Search::PolygonCreateParams::Sort::SortDestination

            attr_reader sort_driving_mode: NextbillionSDK::Models::Skynet::Search::PolygonCreateParams::Sort::sort_driving_mode?

            def sort_driving_mode=: (
              NextbillionSDK::Models::Skynet::Search::PolygonCreateParams::Sort::sort_driving_mode
            ) -> NextbillionSDK::Models::Skynet::Search::PolygonCreateParams::Sort::sort_driving_mode

            def initialize: (
              ?sort_by: NextbillionSDK::Models::Skynet::Search::PolygonCreateParams::Sort::sort_by,
              ?sort_destination: NextbillionSDK::Skynet::Search::PolygonCreateParams::Sort::SortDestination,
              ?sort_driving_mode: NextbillionSDK::Models::Skynet::Search::PolygonCreateParams::Sort::sort_driving_mode
            ) -> void

            def to_hash: -> {
              sort_by: NextbillionSDK::Models::Skynet::Search::PolygonCreateParams::Sort::sort_by,
              sort_destination: NextbillionSDK::Skynet::Search::PolygonCreateParams::Sort::SortDestination,
              sort_driving_mode: NextbillionSDK::Models::Skynet::Search::PolygonCreateParams::Sort::sort_driving_mode
            }

            type sort_by = :distance | :duration | :straight_distance

            module SortBy
              extend NextbillionSDK::Internal::Type::Enum

              DISTANCE: :distance
              DURATION: :duration
              STRAIGHT_DISTANCE: :straight_distance

              def self?.values: -> ::Array[NextbillionSDK::Models::Skynet::Search::PolygonCreateParams::Sort::sort_by]
            end

            type sort_destination = { lat: Float, lon: Float }

            class SortDestination < NextbillionSDK::Internal::Type::BaseModel
              attr_accessor lat: Float

              attr_accessor lon: Float

              def initialize: (lat: Float, lon: Float) -> void

              def to_hash: -> { lat: Float, lon: Float }
            end

            type sort_driving_mode = :car | :truck

            module SortDrivingMode
              extend NextbillionSDK::Internal::Type::Enum

              CAR: :car
              TRUCK: :truck

              def self?.values: -> ::Array[NextbillionSDK::Models::Skynet::Search::PolygonCreateParams::Sort::sort_driving_mode]
            end
          end
        end
      end
    end
  end
end
