configured_endpoints: 95
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/nextbillion-ai%2Fnextbillion-sdk-7ee76f0ff6794db818b352ca1566016118ee6d90e8fec84a363e7bcdbfea27a0.yml
openapi_spec_hash: 6af51daccd4c91b5d04f71c45dbc31d8
config_hash: fcc5bb0df18828b74fd7a59cdcf2a595
