configured_endpoints: 95
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/nextbillion-ai%2Fnextbillion-sdk-b647f1808dda89d18a6340cee497eca5248f6f7d0172dfcf903a6361a1261013.yml
openapi_spec_hash: 6af51daccd4c91b5d04f71c45dbc31d8
config_hash: 297ad5b2a79da3c4bae12d9bce4efcc7
