configured_endpoints: 95
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/nextbillion-ai/nextbillion-sdk-5365fd6e2e5cfe93c210af71b90838abeb5939f182e3c0a23e3c17de3050d961.yml
openapi_spec_hash: 6af51daccd4c91b5d04f71c45dbc31d8
config_hash: 297ad5b2a79da3c4bae12d9bce4efcc7
