configured_endpoints: 95
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/nextbillion-ai%2Fnextbillion-sdk-535d42dd7dd109fcc5d3c625f908cc516de52feb2f740cb6099f7d5f8891c9ac.yml
openapi_spec_hash: c577faef7a08c5057ebba2bfdaee9088
config_hash: d033bac89cdf204a50f8a06fa54a34eb
