module NextbillionSDK
  module Models
    module Skynet
      type asset_update_params =
        {
          key: String,
          cluster: NextbillionSDK::Models::Skynet::AssetUpdateParams::cluster,
          attributes: top,
          description: String,
          meta_data: top,
          name: String,
          tags: ::Array[String]
        }
        & NextbillionSDK::Internal::Type::request_parameters

      class AssetUpdateParams < NextbillionSDK::Internal::Type::BaseModel
        extend NextbillionSDK::Internal::Type::RequestParameters::Converter
        include NextbillionSDK::Internal::Type::RequestParameters

        attr_accessor key: String

        attr_reader cluster: NextbillionSDK::Models::Skynet::AssetUpdateParams::cluster?

        def cluster=: (
          NextbillionSDK::Models::Skynet::AssetUpdateParams::cluster
        ) -> NextbillionSDK::Models::Skynet::AssetUpdateParams::cluster

        attr_reader attributes: top?

        def attributes=: (top) -> top

        attr_reader description: String?

        def description=: (String) -> String

        attr_reader meta_data: top?

        def meta_data=: (top) -> top

        attr_reader name: String?

        def name=: (String) -> String

        attr_reader tags: ::Array[String]?

        def tags=: (::Array[String]) -> ::Array[String]

        def initialize: (
          key: String,
          ?cluster: NextbillionSDK::Models::Skynet::AssetUpdateParams::cluster,
          ?attributes: top,
          ?description: String,
          ?meta_data: top,
          ?name: String,
          ?tags: ::Array[String],
          ?request_options: NextbillionSDK::request_opts
        ) -> void

        def to_hash: -> {
          key: String,
          cluster: NextbillionSDK::Models::Skynet::AssetUpdateParams::cluster,
          attributes: top,
          description: String,
          meta_data: top,
          name: String,
          tags: ::Array[String],
          request_options: NextbillionSDK::RequestOptions
        }

        type cluster = :america

        module Cluster
          extend NextbillionSDK::Internal::Type::Enum

          AMERICA: :america

          def self?.values: -> ::Array[NextbillionSDK::Models::Skynet::AssetUpdateParams::cluster]
        end
      end
    end
  end
end
