module NextbillionSDK
  module Models
    module Skynet
      type config_retrieve_response =
        {
          data: NextbillionSDK::Models::Skynet::ConfigRetrieveResponse::Data,
          message: String,
          status: String
        }

      class ConfigRetrieveResponse < NextbillionSDK::Internal::Type::BaseModel
        attr_reader data: NextbillionSDK::Models::Skynet::ConfigRetrieveResponse::Data?

        def data=: (
          NextbillionSDK::Models::Skynet::ConfigRetrieveResponse::Data
        ) -> NextbillionSDK::Models::Skynet::ConfigRetrieveResponse::Data

        attr_reader message: String?

        def message=: (String) -> String

        attr_reader status: String?

        def status=: (String) -> String

        def initialize: (
          ?data: NextbillionSDK::Models::Skynet::ConfigRetrieveResponse::Data,
          ?message: String,
          ?status: String
        ) -> void

        def to_hash: -> {
          data: NextbillionSDK::Models::Skynet::ConfigRetrieveResponse::Data,
          message: String,
          status: String
        }

        type data =
          {
            config: NextbillionSDK::Models::Skynet::ConfigRetrieveResponse::Data::Config
          }

        class Data < NextbillionSDK::Internal::Type::BaseModel
          attr_reader config: NextbillionSDK::Models::Skynet::ConfigRetrieveResponse::Data::Config?

          def config=: (
            NextbillionSDK::Models::Skynet::ConfigRetrieveResponse::Data::Config
          ) -> NextbillionSDK::Models::Skynet::ConfigRetrieveResponse::Data::Config

          def initialize: (
            ?config: NextbillionSDK::Models::Skynet::ConfigRetrieveResponse::Data::Config
          ) -> void

          def to_hash: -> {
            config: NextbillionSDK::Models::Skynet::ConfigRetrieveResponse::Data::Config
          }

          type config = { webhook: ::Array[String] }

          class Config < NextbillionSDK::Internal::Type::BaseModel
            attr_reader webhook: ::Array[String]?

            def webhook=: (::Array[String]) -> ::Array[String]

            def initialize: (?webhook: ::Array[String]) -> void

            def to_hash: -> { webhook: ::Array[String] }
          end
        end
      end
    end
  end
end
