module NextbillionSDK
  module Models
    module Skynet
      type skynet_monitor =
        {
          id: String,
          created_at: Integer,
          description: String,
          geofence_config: NextbillionSDK::Skynet::SkynetMonitor::GeofenceConfig,
          geofences: ::Array[String],
          idle_config: NextbillionSDK::Skynet::SkynetMonitor::IdleConfig,
          match_filter: NextbillionSDK::Skynet::SkynetMonitor::MatchFilter,
          meta_data: top,
          name: String,
          speeding_config: NextbillionSDK::Skynet::SkynetMonitor::SpeedingConfig,
          tags: ::Array[String],
          type: NextbillionSDK::Models::Skynet::SkynetMonitor::type_,
          updated_at: Integer
        }

      class SkynetMonitor < NextbillionSDK::Internal::Type::BaseModel
        attr_reader id: String?

        def id=: (String) -> String

        attr_reader created_at: Integer?

        def created_at=: (Integer) -> Integer

        attr_reader description: String?

        def description=: (String) -> String

        attr_reader geofence_config: NextbillionSDK::Skynet::SkynetMonitor::GeofenceConfig?

        def geofence_config=: (
          NextbillionSDK::Skynet::SkynetMonitor::GeofenceConfig
        ) -> NextbillionSDK::Skynet::SkynetMonitor::GeofenceConfig

        attr_reader geofences: ::Array[String]?

        def geofences=: (::Array[String]) -> ::Array[String]

        attr_reader idle_config: NextbillionSDK::Skynet::SkynetMonitor::IdleConfig?

        def idle_config=: (
          NextbillionSDK::Skynet::SkynetMonitor::IdleConfig
        ) -> NextbillionSDK::Skynet::SkynetMonitor::IdleConfig

        attr_reader match_filter: NextbillionSDK::Skynet::SkynetMonitor::MatchFilter?

        def match_filter=: (
          NextbillionSDK::Skynet::SkynetMonitor::MatchFilter
        ) -> NextbillionSDK::Skynet::SkynetMonitor::MatchFilter

        attr_reader meta_data: top?

        def meta_data=: (top) -> top

        attr_reader name: String?

        def name=: (String) -> String

        attr_reader speeding_config: NextbillionSDK::Skynet::SkynetMonitor::SpeedingConfig?

        def speeding_config=: (
          NextbillionSDK::Skynet::SkynetMonitor::SpeedingConfig
        ) -> NextbillionSDK::Skynet::SkynetMonitor::SpeedingConfig

        attr_reader tags: ::Array[String]?

        def tags=: (::Array[String]) -> ::Array[String]

        attr_reader type: NextbillionSDK::Models::Skynet::SkynetMonitor::type_?

        def type=: (
          NextbillionSDK::Models::Skynet::SkynetMonitor::type_
        ) -> NextbillionSDK::Models::Skynet::SkynetMonitor::type_

        attr_reader updated_at: Integer?

        def updated_at=: (Integer) -> Integer

        def initialize: (
          ?id: String,
          ?created_at: Integer,
          ?description: String,
          ?geofence_config: NextbillionSDK::Skynet::SkynetMonitor::GeofenceConfig,
          ?geofences: ::Array[String],
          ?idle_config: NextbillionSDK::Skynet::SkynetMonitor::IdleConfig,
          ?match_filter: NextbillionSDK::Skynet::SkynetMonitor::MatchFilter,
          ?meta_data: top,
          ?name: String,
          ?speeding_config: NextbillionSDK::Skynet::SkynetMonitor::SpeedingConfig,
          ?tags: ::Array[String],
          ?type: NextbillionSDK::Models::Skynet::SkynetMonitor::type_,
          ?updated_at: Integer
        ) -> void

        def to_hash: -> {
          id: String,
          created_at: Integer,
          description: String,
          geofence_config: NextbillionSDK::Skynet::SkynetMonitor::GeofenceConfig,
          geofences: ::Array[String],
          idle_config: NextbillionSDK::Skynet::SkynetMonitor::IdleConfig,
          match_filter: NextbillionSDK::Skynet::SkynetMonitor::MatchFilter,
          meta_data: top,
          name: String,
          speeding_config: NextbillionSDK::Skynet::SkynetMonitor::SpeedingConfig,
          tags: ::Array[String],
          type: NextbillionSDK::Models::Skynet::SkynetMonitor::type_,
          updated_at: Integer
        }

        type geofence_config = { geofence_ids: ::Array[String] }

        class GeofenceConfig < NextbillionSDK::Internal::Type::BaseModel
          attr_reader geofence_ids: ::Array[String]?

          def geofence_ids=: (::Array[String]) -> ::Array[String]

          def initialize: (?geofence_ids: ::Array[String]) -> void

          def to_hash: -> { geofence_ids: ::Array[String] }
        end

        type idle_config =
          { distance_tolerance: Float, time_tolerance: Integer }

        class IdleConfig < NextbillionSDK::Internal::Type::BaseModel
          attr_reader distance_tolerance: Float?

          def distance_tolerance=: (Float) -> Float

          attr_reader time_tolerance: Integer?

          def time_tolerance=: (Integer) -> Integer

          def initialize: (
            ?distance_tolerance: Float,
            ?time_tolerance: Integer
          ) -> void

          def to_hash: -> { distance_tolerance: Float, time_tolerance: Integer }
        end

        type match_filter =
          { include_all_of_attributes: top, include_any_of_attributes: top }

        class MatchFilter < NextbillionSDK::Internal::Type::BaseModel
          attr_reader include_all_of_attributes: top?

          def include_all_of_attributes=: (top) -> top

          attr_reader include_any_of_attributes: top?

          def include_any_of_attributes=: (top) -> top

          def initialize: (
            ?include_all_of_attributes: top,
            ?include_any_of_attributes: top
          ) -> void

          def to_hash: -> {
            include_all_of_attributes: top,
            include_any_of_attributes: top
          }
        end

        type speeding_config =
          {
            customer_speed_limit: Integer,
            time_tolerance: Integer,
            use_admin_speed_limit: bool
          }

        class SpeedingConfig < NextbillionSDK::Internal::Type::BaseModel
          attr_reader customer_speed_limit: Integer?

          def customer_speed_limit=: (Integer) -> Integer

          attr_reader time_tolerance: Integer?

          def time_tolerance=: (Integer) -> Integer

          attr_reader use_admin_speed_limit: bool?

          def use_admin_speed_limit=: (bool) -> bool

          def initialize: (
            ?customer_speed_limit: Integer,
            ?time_tolerance: Integer,
            ?use_admin_speed_limit: bool
          ) -> void

          def to_hash: -> {
            customer_speed_limit: Integer,
            time_tolerance: Integer,
            use_admin_speed_limit: bool
          }
        end

        type type_ = :enter | :exit | :enter_and_exit | :speeding | :idle

        module Type
          extend NextbillionSDK::Internal::Type::Enum

          ENTER: :enter
          EXIT: :exit
          ENTER_AND_EXIT: :enter_and_exit
          SPEEDING: :speeding
          IDLE: :idle

          def self?.values: -> ::Array[NextbillionSDK::Models::Skynet::SkynetMonitor::type_]
        end
      end
    end
  end
end
