module NextbillionSDK
  module Models
    module Skynet
      type trip_get_summary_params =
        {
          key: String,
          cluster: NextbillionSDK::Models::Skynet::TripGetSummaryParams::cluster
        }
        & NextbillionSDK::Internal::Type::request_parameters

      class TripGetSummaryParams < NextbillionSDK::Internal::Type::BaseModel
        extend NextbillionSDK::Internal::Type::RequestParameters::Converter
        include NextbillionSDK::Internal::Type::RequestParameters

        attr_accessor key: String

        attr_reader cluster: NextbillionSDK::Models::Skynet::TripGetSummaryParams::cluster?

        def cluster=: (
          NextbillionSDK::Models::Skynet::TripGetSummaryParams::cluster
        ) -> NextbillionSDK::Models::Skynet::TripGetSummaryParams::cluster

        def initialize: (
          key: String,
          ?cluster: NextbillionSDK::Models::Skynet::TripGetSummaryParams::cluster,
          ?request_options: NextbillionSDK::request_opts
        ) -> void

        def to_hash: -> {
          key: String,
          cluster: NextbillionSDK::Models::Skynet::TripGetSummaryParams::cluster,
          request_options: NextbillionSDK::RequestOptions
        }

        type cluster = :america

        module Cluster
          extend NextbillionSDK::Internal::Type::Enum

          AMERICA: :america

          def self?.values: -> ::Array[NextbillionSDK::Models::Skynet::TripGetSummaryParams::cluster]
        end
      end
    end
  end
end
