module Nextbillionai
  module Resources
    class Optimization
      class V2
        def retrieve_result: (
          id: String,
          key: String,
          ?request_options: Nextbillionai::request_opts
        ) -> Nextbillionai::Models::Optimization::V2RetrieveResultResponse

        def submit: (
          key: String,
          locations: Nextbillionai::Optimization::V2SubmitParams::Locations,
          vehicles: ::Array[Nextbillionai::Optimization::Vehicle],
          ?cost_matrix: ::Array[::Array[Integer]],
          ?depots: ::Array[Nextbillionai::Optimization::V2SubmitParams::Depot],
          ?description: String,
          ?distance_matrix: ::Array[::Array[Integer]],
          ?duration_matrix: ::Array[::Array[Integer]],
          ?existing_solution_id: String,
          ?jobs: ::Array[Nextbillionai::Optimization::Job],
          ?options: Nextbillionai::Optimization::V2SubmitParams::Options,
          ?relations: ::Array[Nextbillionai::Optimization::V2SubmitParams::Relation],
          ?shipments: ::Array[Nextbillionai::Optimization::Shipment],
          ?solution: ::Array[Nextbillionai::Optimization::V2SubmitParams::Solution],
          ?unassigned: Nextbillionai::Optimization::V2SubmitParams::Unassigned,
          ?zones: ::Array[Nextbillionai::Optimization::V2SubmitParams::Zone],
          ?request_options: Nextbillionai::request_opts
        ) -> Nextbillionai::PostResponse

        def initialize: (client: Nextbillionai::Client) -> void
      end
    end
  end
end
