module Nextbillionai
  module Models
    module Fleetify
      type document_template_list_params =
        { key: String } & Nextbillionai::Internal::Type::request_parameters

      class DocumentTemplateListParams < Nextbillionai::Internal::Type::BaseModel
        extend Nextbillionai::Internal::Type::RequestParameters::Converter
        include Nextbillionai::Internal::Type::RequestParameters

        attr_accessor key: String

        def initialize: (
          key: String,
          ?request_options: Nextbillionai::request_opts
        ) -> void

        def to_hash: -> {
          key: String,
          request_options: Nextbillionai::RequestOptions
        }
      end
    end
  end
end
