module Nextbillionai
  module Models
    module Optimization
      type driver_assignment_assign_response =
        {
          message: String,
          result: Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result,
          status: Integer
        }

      class DriverAssignmentAssignResponse < Nextbillionai::Internal::Type::BaseModel
        attr_reader message: String?

        def message=: (String) -> String

        attr_reader result: Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result?

        def result=: (
          Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result
        ) -> Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result

        attr_reader status: Integer?

        def status=: (Integer) -> Integer

        def initialize: (
          ?message: String,
          ?result: Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result,
          ?status: Integer
        ) -> void

        def to_hash: -> {
          message: String,
          result: Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result,
          status: Integer
        }

        type result =
          {
            alternate_assignments: ::Array[Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result::AlternateAssignment],
            available_vehicles: ::Array[String],
            trips: ::Array[Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result::Trip],
            unassigned_orders: ::Array[Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result::UnassignedOrder]
          }

        class Result < Nextbillionai::Internal::Type::BaseModel
          attr_reader alternate_assignments: ::Array[Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result::AlternateAssignment]?

          def alternate_assignments=: (
            ::Array[Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result::AlternateAssignment]
          ) -> ::Array[Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result::AlternateAssignment]

          attr_reader available_vehicles: ::Array[String]?

          def available_vehicles=: (::Array[String]) -> ::Array[String]

          attr_reader trips: ::Array[Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result::Trip]?

          def trips=: (
            ::Array[Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result::Trip]
          ) -> ::Array[Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result::Trip]

          attr_reader unassigned_orders: ::Array[Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result::UnassignedOrder]?

          def unassigned_orders=: (
            ::Array[Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result::UnassignedOrder]
          ) -> ::Array[Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result::UnassignedOrder]

          def initialize: (
            ?alternate_assignments: ::Array[Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result::AlternateAssignment],
            ?available_vehicles: ::Array[String],
            ?trips: ::Array[Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result::Trip],
            ?unassigned_orders: ::Array[Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result::UnassignedOrder]
          ) -> void

          def to_hash: -> {
            alternate_assignments: ::Array[Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result::AlternateAssignment],
            available_vehicles: ::Array[String],
            trips: ::Array[Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result::Trip],
            unassigned_orders: ::Array[Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result::UnassignedOrder]
          }

          type alternate_assignment =
            {
              assignments: ::Array[Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result::AlternateAssignment::Assignment],
              order_id: String
            }

          class AlternateAssignment < Nextbillionai::Internal::Type::BaseModel
            attr_reader assignments: ::Array[Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result::AlternateAssignment::Assignment]?

            def assignments=: (
              ::Array[Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result::AlternateAssignment::Assignment]
            ) -> ::Array[Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result::AlternateAssignment::Assignment]

            attr_reader order_id: String?

            def order_id=: (String) -> String

            def initialize: (
              ?assignments: ::Array[Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result::AlternateAssignment::Assignment],
              ?order_id: String
            ) -> void

            def to_hash: -> {
              assignments: ::Array[Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result::AlternateAssignment::Assignment],
              order_id: String
            }

            type assignment = { pickup_eta: Integer, vehicle_id: String }

            class Assignment < Nextbillionai::Internal::Type::BaseModel
              attr_reader pickup_eta: Integer?

              def pickup_eta=: (Integer) -> Integer

              attr_reader vehicle_id: String?

              def vehicle_id=: (String) -> String

              def initialize: (
                ?pickup_eta: Integer,
                ?vehicle_id: String
              ) -> void

              def to_hash: -> { pickup_eta: Integer, vehicle_id: String }
            end
          end

          type trip =
            {
              trip_id: String,
              vehicle: Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result::Trip::Vehicle
            }

          class Trip < Nextbillionai::Internal::Type::BaseModel
            attr_reader trip_id: String?

            def trip_id=: (String) -> String

            attr_reader vehicle: Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result::Trip::Vehicle?

            def vehicle=: (
              Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result::Trip::Vehicle
            ) -> Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result::Trip::Vehicle

            def initialize: (
              ?trip_id: String,
              ?vehicle: Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result::Trip::Vehicle
            ) -> void

            def to_hash: -> {
              trip_id: String,
              vehicle: Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result::Trip::Vehicle
            }

            type vehicle =
              {
                id: String,
                steps: Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result::Trip::Vehicle::Steps,
                vehicle_current_location: Nextbillionai::Optimization::Location
              }

            class Vehicle < Nextbillionai::Internal::Type::BaseModel
              attr_reader id: String?

              def id=: (String) -> String

              attr_reader steps: Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result::Trip::Vehicle::Steps?

              def steps=: (
                Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result::Trip::Vehicle::Steps
              ) -> Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result::Trip::Vehicle::Steps

              attr_reader vehicle_current_location: Nextbillionai::Optimization::Location?

              def vehicle_current_location=: (
                Nextbillionai::Optimization::Location
              ) -> Nextbillionai::Optimization::Location

              def initialize: (
                ?id: String,
                ?steps: Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result::Trip::Vehicle::Steps,
                ?vehicle_current_location: Nextbillionai::Optimization::Location
              ) -> void

              def to_hash: -> {
                id: String,
                steps: Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result::Trip::Vehicle::Steps,
                vehicle_current_location: Nextbillionai::Optimization::Location
              }

              type steps =
                {
                  distance: Integer,
                  eta: Integer,
                  location: Nextbillionai::Optimization::Location,
                  order_id: String,
                  type: Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result::Trip::Vehicle::Steps::type_
                }

              class Steps < Nextbillionai::Internal::Type::BaseModel
                attr_reader distance: Integer?

                def distance=: (Integer) -> Integer

                attr_reader eta: Integer?

                def eta=: (Integer) -> Integer

                attr_reader location: Nextbillionai::Optimization::Location?

                def location=: (
                  Nextbillionai::Optimization::Location
                ) -> Nextbillionai::Optimization::Location

                attr_reader order_id: String?

                def order_id=: (String) -> String

                attr_reader type: Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result::Trip::Vehicle::Steps::type_?

                def type=: (
                  Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result::Trip::Vehicle::Steps::type_
                ) -> Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result::Trip::Vehicle::Steps::type_

                def initialize: (
                  ?distance: Integer,
                  ?eta: Integer,
                  ?location: Nextbillionai::Optimization::Location,
                  ?order_id: String,
                  ?type: Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result::Trip::Vehicle::Steps::type_
                ) -> void

                def to_hash: -> {
                  distance: Integer,
                  eta: Integer,
                  location: Nextbillionai::Optimization::Location,
                  order_id: String,
                  type: Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result::Trip::Vehicle::Steps::type_
                }

                type type_ = :pickup | :dropoff | :ongoing

                module Type
                  extend Nextbillionai::Internal::Type::Enum

                  PICKUP: :pickup
                  DROPOFF: :dropoff
                  ONGOING: :ongoing

                  def self?.values: -> ::Array[Nextbillionai::Models::Optimization::DriverAssignmentAssignResponse::Result::Trip::Vehicle::Steps::type_]
                end
              end
            end
          end

          type unassigned_order =
            { order_id: String, unassigned_reason: String }

          class UnassignedOrder < Nextbillionai::Internal::Type::BaseModel
            attr_reader order_id: String?

            def order_id=: (String) -> String

            attr_reader unassigned_reason: String?

            def unassigned_reason=: (String) -> String

            def initialize: (
              ?order_id: String,
              ?unassigned_reason: String
            ) -> void

            def to_hash: -> { order_id: String, unassigned_reason: String }
          end
        end
      end
    end
  end
end
