module Nextbillionai
  module Models
    module Optimization
      type location = { lat: Float, lon: Float }

      class Location < Nextbillionai::Internal::Type::BaseModel
        attr_accessor lat: Float

        attr_accessor lon: Float

        def initialize: (lat: Float, lon: Float) -> void

        def to_hash: -> { lat: Float, lon: Float }
      end
    end
  end
end
