module NextbillionSDK
  class Client < NextbillionSDK::Internal::Transport::BaseClient
    DEFAULT_MAX_RETRIES: 2

    DEFAULT_TIMEOUT_IN_SECONDS: Float

    DEFAULT_INITIAL_RETRY_DELAY: Float

    DEFAULT_MAX_RETRY_DELAY: Float

    attr_reader api_key: String

    attr_reader fleetify: NextbillionSDK::Resources::Fleetify

    attr_reader skynet: NextbillionSDK::Resources::Skynet

    attr_reader geocode: NextbillionSDK::Resources::Geocode

    attr_reader optimization: NextbillionSDK::Resources::Optimization

    attr_reader geofence: NextbillionSDK::Resources::Geofence

    attr_reader discover: NextbillionSDK::Resources::Discover

    attr_reader browse: NextbillionSDK::Resources::Browse

    attr_reader mdm: NextbillionSDK::Resources::Mdm

    attr_reader isochrone: NextbillionSDK::Resources::Isochrone

    attr_reader restrictions: NextbillionSDK::Resources::Restrictions

    attr_reader restrictions_items: NextbillionSDK::Resources::RestrictionsItems

    attr_reader distance_matrix: NextbillionSDK::Resources::DistanceMatrix

    attr_reader autocomplete: NextbillionSDK::Resources::Autocomplete

    attr_reader navigation: NextbillionSDK::Resources::Navigation

    attr_reader map: NextbillionSDK::Resources::Map

    attr_reader autosuggest: NextbillionSDK::Resources::Autosuggest

    attr_reader directions: NextbillionSDK::Resources::Directions

    attr_reader batch: NextbillionSDK::Resources::Batch

    attr_reader multigeocode: NextbillionSDK::Resources::Multigeocode

    attr_reader revgeocode: NextbillionSDK::Resources::Revgeocode

    attr_reader route_report: NextbillionSDK::Resources::RouteReport

    attr_reader snap_to_roads: NextbillionSDK::Resources::SnapToRoads

    attr_reader postalcode: NextbillionSDK::Resources::Postalcode

    attr_reader lookup: NextbillionSDK::Resources::Lookup

    attr_reader areas: NextbillionSDK::Resources::Areas

    private def auth_query: -> ::Hash[String, String]

    def initialize: (
      ?api_key: String?,
      ?base_url: String?,
      ?max_retries: Integer,
      ?timeout: Float,
      ?initial_retry_delay: Float,
      ?max_retry_delay: Float
    ) -> void
  end
end
