module NextbillionSDK
  class Access = NextbillionSDK::Models::Access

  class Address = NextbillionSDK::Models::Address

  class AreaListParams = NextbillionSDK::Models::AreaListParams

  class AutocompleteSuggestParams = NextbillionSDK::Models::AutocompleteSuggestParams

  class AutosuggestSuggestParams = NextbillionSDK::Models::AutosuggestSuggestParams

  class BatchCreateParams = NextbillionSDK::Models::BatchCreateParams

  class BatchRetrieveParams = NextbillionSDK::Models::BatchRetrieveParams

  class BrowseSearchParams = NextbillionSDK::Models::BrowseSearchParams

  class Categories = NextbillionSDK::Models::Categories

  class ContactObject = NextbillionSDK::Models::ContactObject

  class Contacts = NextbillionSDK::Models::Contacts

  class DirectionComputeRouteParams = NextbillionSDK::Models::DirectionComputeRouteParams

  class DiscoverRetrieveParams = NextbillionSDK::Models::DiscoverRetrieveParams

  module DistanceMatrix = NextbillionSDK::Models::DistanceMatrix

  module Fleetify = NextbillionSDK::Models::Fleetify

  class GeocodeBatchCreateParams = NextbillionSDK::Models::GeocodeBatchCreateParams

  class GeocodeRetrieveParams = NextbillionSDK::Models::GeocodeRetrieveParams

  class GeocodeStructuredRetrieveParams = NextbillionSDK::Models::GeocodeStructuredRetrieveParams

  module Geofence = NextbillionSDK::Models::Geofence

  class GeofenceAPI = NextbillionSDK::Models::GeofenceAPI

  class GeofenceContainsParams = NextbillionSDK::Models::GeofenceContainsParams

  class GeofenceCreateParams = NextbillionSDK::Models::GeofenceCreateParams

  class GeofenceDeleteParams = NextbillionSDK::Models::GeofenceDeleteParams

  class GeofenceEntityCreate = NextbillionSDK::Models::GeofenceEntityCreate

  class GeofenceListParams = NextbillionSDK::Models::GeofenceListParams

  class GeofenceRetrieveParams = NextbillionSDK::Models::GeofenceRetrieveParams

  class GeofenceUpdateParams = NextbillionSDK::Models::GeofenceUpdateParams

  class IsochroneComputeParams = NextbillionSDK::Models::IsochroneComputeParams

  class LookupByIDParams = NextbillionSDK::Models::LookupByIDParams

  class MapCreateSegmentParams = NextbillionSDK::Models::MapCreateSegmentParams

  class MapView = NextbillionSDK::Models::MapView

  class MdmCreateDistanceMatrixParams = NextbillionSDK::Models::MdmCreateDistanceMatrixParams

  class MdmGetDistanceMatrixStatusParams = NextbillionSDK::Models::MdmGetDistanceMatrixStatusParams

  module Multigeocode = NextbillionSDK::Models::Multigeocode

  class MultigeocodeSearchParams = NextbillionSDK::Models::MultigeocodeSearchParams

  class NavigationRetrieveRouteParams = NextbillionSDK::Models::NavigationRetrieveRouteParams

  module Optimization = NextbillionSDK::Models::Optimization

  class OptimizationComputeParams = NextbillionSDK::Models::OptimizationComputeParams

  class OptimizationReOptimizeParams = NextbillionSDK::Models::OptimizationReOptimizeParams

  class Position = NextbillionSDK::Models::Position

  class PostalcodeRetrieveCoordinatesParams = NextbillionSDK::Models::PostalcodeRetrieveCoordinatesParams

  class PostResponse = NextbillionSDK::Models::PostResponse

  class RestrictionCreateParams = NextbillionSDK::Models::RestrictionCreateParams

  class RestrictionDeleteParams = NextbillionSDK::Models::RestrictionDeleteParams

  class RestrictionListByBboxParams = NextbillionSDK::Models::RestrictionListByBboxParams

  class RestrictionListParams = NextbillionSDK::Models::RestrictionListParams

  class RestrictionRetrieveParams = NextbillionSDK::Models::RestrictionRetrieveParams

  class RestrictionSetStateParams = NextbillionSDK::Models::RestrictionSetStateParams

  class RestrictionsItemListParams = NextbillionSDK::Models::RestrictionsItemListParams

  class RestrictionUpdateParams = NextbillionSDK::Models::RestrictionUpdateParams

  class RevgeocodeRetrieveParams = NextbillionSDK::Models::RevgeocodeRetrieveParams

  class RichGroupRequest = NextbillionSDK::Models::RichGroupRequest

  class RichGroupResponse = NextbillionSDK::Models::RichGroupResponse

  class RouteReportCreateParams = NextbillionSDK::Models::RouteReportCreateParams

  module Skynet = NextbillionSDK::Models::Skynet

  class SkynetSubscribeParams = NextbillionSDK::Models::SkynetSubscribeParams

  class SnapToRoadSnapParams = NextbillionSDK::Models::SnapToRoadSnapParams
end
