module NextbillionSDK
  module Models
    module Fleetify
      type document_template_delete_response = { msg: String, status: Integer }

      class DocumentTemplateDeleteResponse < NextbillionSDK::Internal::Type::BaseModel
        attr_reader msg: String?

        def msg=: (String) -> String

        attr_reader status: Integer?

        def status=: (Integer) -> Integer

        def initialize: (?msg: String, ?status: Integer) -> void

        def to_hash: -> { msg: String, status: Integer }
      end
    end
  end
end
