module NextbillionSDK
  module Models
    module Fleetify
      type document_template_content_response =
        {
          label: String,
          meta: NextbillionSDK::Fleetify::DocumentTemplateContentResponse::Meta,
          name: String,
          required: bool,
          type: String,
          validation: NextbillionSDK::Fleetify::DocumentTemplateContentResponse::Validation
        }

      class DocumentTemplateContentResponse < NextbillionSDK::Internal::Type::BaseModel
        attr_reader label: String?

        def label=: (String) -> String

        attr_reader meta: NextbillionSDK::Fleetify::DocumentTemplateContentResponse::Meta?

        def meta=: (
          NextbillionSDK::Fleetify::DocumentTemplateContentResponse::Meta
        ) -> NextbillionSDK::Fleetify::DocumentTemplateContentResponse::Meta

        attr_reader name: String?

        def name=: (String) -> String

        attr_reader required: bool?

        def required=: (bool) -> bool

        attr_reader type: String?

        def type=: (String) -> String

        attr_reader validation: NextbillionSDK::Fleetify::DocumentTemplateContentResponse::Validation?

        def validation=: (
          NextbillionSDK::Fleetify::DocumentTemplateContentResponse::Validation
        ) -> NextbillionSDK::Fleetify::DocumentTemplateContentResponse::Validation

        def initialize: (
          ?label: String,
          ?meta: NextbillionSDK::Fleetify::DocumentTemplateContentResponse::Meta,
          ?name: String,
          ?required: bool,
          ?type: String,
          ?validation: NextbillionSDK::Fleetify::DocumentTemplateContentResponse::Validation
        ) -> void

        def to_hash: -> {
          label: String,
          meta: NextbillionSDK::Fleetify::DocumentTemplateContentResponse::Meta,
          name: String,
          required: bool,
          type: String,
          validation: NextbillionSDK::Fleetify::DocumentTemplateContentResponse::Validation
        }

        type meta =
          {
            options: ::Array[NextbillionSDK::Fleetify::DocumentTemplateContentResponse::Meta::Option]
          }

        class Meta < NextbillionSDK::Internal::Type::BaseModel
          attr_reader options: ::Array[NextbillionSDK::Fleetify::DocumentTemplateContentResponse::Meta::Option]?

          def options=: (
            ::Array[NextbillionSDK::Fleetify::DocumentTemplateContentResponse::Meta::Option]
          ) -> ::Array[NextbillionSDK::Fleetify::DocumentTemplateContentResponse::Meta::Option]

          def initialize: (
            ?options: ::Array[NextbillionSDK::Fleetify::DocumentTemplateContentResponse::Meta::Option]
          ) -> void

          def to_hash: -> {
            options: ::Array[NextbillionSDK::Fleetify::DocumentTemplateContentResponse::Meta::Option]
          }

          type option = { label: String, value: String }

          class Option < NextbillionSDK::Internal::Type::BaseModel
            attr_reader label: String?

            def label=: (String) -> String

            attr_reader value: String?

            def value=: (String) -> String

            def initialize: (?label: String, ?value: String) -> void

            def to_hash: -> { label: String, value: String }
          end
        end

        type validation =
          { max: Integer, max_items: String, min: Integer, min_items: String }

        class Validation < NextbillionSDK::Internal::Type::BaseModel
          attr_reader max: Integer?

          def max=: (Integer) -> Integer

          attr_reader max_items: String?

          def max_items=: (String) -> String

          attr_reader min: Integer?

          def min=: (Integer) -> Integer

          attr_reader min_items: String?

          def min_items=: (String) -> String

          def initialize: (
            ?max: Integer,
            ?max_items: String,
            ?min: Integer,
            ?min_items: String
          ) -> void

          def to_hash: -> {
            max: Integer,
            max_items: String,
            min: Integer,
            min_items: String
          }
        end
      end
    end
  end
end
