module NextbillionSDK
  module Models
    module Fleetify
      type routing_response =
        {
          approaches: String,
          avoid: String,
          hazmat_type: String,
          mode: String,
          truck_axle_load: String,
          truck_size: String,
          truck_weight: String
        }

      class RoutingResponse < NextbillionSDK::Internal::Type::BaseModel
        attr_reader approaches: String?

        def approaches=: (String) -> String

        attr_reader avoid: String?

        def avoid=: (String) -> String

        attr_reader hazmat_type: String?

        def hazmat_type=: (String) -> String

        attr_reader mode: String?

        def mode=: (String) -> String

        attr_reader truck_axle_load: String?

        def truck_axle_load=: (String) -> String

        attr_reader truck_size: String?

        def truck_size=: (String) -> String

        attr_reader truck_weight: String?

        def truck_weight=: (String) -> String

        def initialize: (
          ?approaches: String,
          ?avoid: String,
          ?hazmat_type: String,
          ?mode: String,
          ?truck_axle_load: String,
          ?truck_size: String,
          ?truck_weight: String
        ) -> void

        def to_hash: -> {
          approaches: String,
          avoid: String,
          hazmat_type: String,
          mode: String,
          truck_axle_load: String,
          truck_size: String,
          truck_weight: String
        }
      end
    end
  end
end
