module NextbillionSDK
  module Models
    module Geofence
      type console_search_params =
        { query: String } & NextbillionSDK::Internal::Type::request_parameters

      class ConsoleSearchParams < NextbillionSDK::Internal::Type::BaseModel
        extend NextbillionSDK::Internal::Type::RequestParameters::Converter
        include NextbillionSDK::Internal::Type::RequestParameters

        attr_accessor query: String

        def initialize: (
          query: String,
          ?request_options: NextbillionSDK::request_opts
        ) -> void

        def to_hash: -> {
          query: String,
          request_options: NextbillionSDK::RequestOptions
        }
      end
    end
  end
end
