module NextbillionSDK
  module Models
    module Geofence
      type console_preview_response =
        {
          data: NextbillionSDK::Models::Geofence::ConsolePreviewResponse::Data,
          message: String
        }

      class ConsolePreviewResponse < NextbillionSDK::Internal::Type::BaseModel
        attr_reader data: NextbillionSDK::Models::Geofence::ConsolePreviewResponse::Data?

        def data=: (
          NextbillionSDK::Models::Geofence::ConsolePreviewResponse::Data
        ) -> NextbillionSDK::Models::Geofence::ConsolePreviewResponse::Data

        attr_reader message: String?

        def message=: (String) -> String

        def initialize: (
          ?data: NextbillionSDK::Models::Geofence::ConsolePreviewResponse::Data,
          ?message: String
        ) -> void

        def to_hash: -> {
          data: NextbillionSDK::Models::Geofence::ConsolePreviewResponse::Data,
          message: String
        }

        type data = { geojson: NextbillionSDK::Geofence::PolygonGeojson }

        class Data < NextbillionSDK::Internal::Type::BaseModel
          attr_reader geojson: NextbillionSDK::Geofence::PolygonGeojson?

          def geojson=: (
            NextbillionSDK::Geofence::PolygonGeojson
          ) -> NextbillionSDK::Geofence::PolygonGeojson

          def initialize: (
            ?geojson: NextbillionSDK::Geofence::PolygonGeojson
          ) -> void

          def to_hash: -> { geojson: NextbillionSDK::Geofence::PolygonGeojson }
        end
      end
    end
  end
end
