module NextbillionSDK
  module Models
    module Geofence
      type console_search_response =
        {
          data: NextbillionSDK::Models::Geofence::ConsoleSearchResponse::Data,
          status: String
        }

      class ConsoleSearchResponse < NextbillionSDK::Internal::Type::BaseModel
        attr_accessor data: NextbillionSDK::Models::Geofence::ConsoleSearchResponse::Data

        attr_accessor status: String

        def initialize: (
          data: NextbillionSDK::Models::Geofence::ConsoleSearchResponse::Data,
          status: String
        ) -> void

        def to_hash: -> {
          data: NextbillionSDK::Models::Geofence::ConsoleSearchResponse::Data,
          status: String
        }

        type data =
          {
            result: ::Array[NextbillionSDK::Models::Geofence::ConsoleSearchResponse::Data::Result]
          }

        class Data < NextbillionSDK::Internal::Type::BaseModel
          attr_accessor result: ::Array[NextbillionSDK::Models::Geofence::ConsoleSearchResponse::Data::Result]

          def initialize: (
            result: ::Array[NextbillionSDK::Models::Geofence::ConsoleSearchResponse::Data::Result]
          ) -> void

          def to_hash: -> {
            result: ::Array[NextbillionSDK::Models::Geofence::ConsoleSearchResponse::Data::Result]
          }

          type result = { id: String, name: String }

          class Result < NextbillionSDK::Internal::Type::BaseModel
            attr_accessor id: String

            attr_accessor name: String

            def initialize: (id: String, name: String) -> void

            def to_hash: -> { id: String, name: String }
          end
        end
      end
    end
  end
end
