module Nextbillionai
  module Resources
    class DistanceMatrix
      class Json
        def create: (?request_options: Nextbillionai::request_opts) -> nil

        def retrieve: (
          destinations: String,
          key: String,
          origins: String,
          ?approaches: Nextbillionai::Models::DistanceMatrix::JsonRetrieveParams::approaches,
          ?avoid: Nextbillionai::Models::DistanceMatrix::JsonRetrieveParams::avoid,
          ?bearings: String,
          ?mode: Nextbillionai::Models::DistanceMatrix::JsonRetrieveParams::mode,
          ?route_failed_prompt: bool,
          ?request_options: Nextbillionai::request_opts
        ) -> Nextbillionai::Models::DistanceMatrix::JsonRetrieveResponse

        def initialize: (client: Nextbillionai::Client) -> void
      end
    end
  end
end
