module Nextbillionai
  module Models
    module Geofence
      type batch_list_response =
        {
          data: Nextbillionai::Models::Geofence::BatchListResponse::Data,
          status: String
        }

      class BatchListResponse < Nextbillionai::Internal::Type::BaseModel
        attr_accessor data: Nextbillionai::Models::Geofence::BatchListResponse::Data

        attr_accessor status: String

        def initialize: (
          data: Nextbillionai::Models::Geofence::BatchListResponse::Data,
          status: String
        ) -> void

        def to_hash: -> {
          data: Nextbillionai::Models::Geofence::BatchListResponse::Data,
          status: String
        }

        type data = { list: ::Array[Nextbillionai::GeofenceAPI] }

        class Data < Nextbillionai::Internal::Type::BaseModel
          attr_accessor list: ::Array[Nextbillionai::GeofenceAPI]

          def initialize: (list: ::Array[Nextbillionai::GeofenceAPI]) -> void

          def to_hash: -> { list: ::Array[Nextbillionai::GeofenceAPI] }
        end
      end
    end
  end
end
