module Nextbillionai
  module Models
    module Geofence
      type console_search_params =
        { query: String } & Nextbillionai::Internal::Type::request_parameters

      class ConsoleSearchParams < Nextbillionai::Internal::Type::BaseModel
        extend Nextbillionai::Internal::Type::RequestParameters::Converter
        include Nextbillionai::Internal::Type::RequestParameters

        attr_accessor query: String

        def initialize: (
          query: String,
          ?request_options: Nextbillionai::request_opts
        ) -> void

        def to_hash: -> {
          query: String,
          request_options: Nextbillionai::RequestOptions
        }
      end
    end
  end
end
