module Nextbillionai
  module Models
    module Geofence
      type console_preview_response =
        {
          data: Nextbillionai::Models::Geofence::ConsolePreviewResponse::Data,
          message: String
        }

      class ConsolePreviewResponse < Nextbillionai::Internal::Type::BaseModel
        attr_reader data: Nextbillionai::Models::Geofence::ConsolePreviewResponse::Data?

        def data=: (
          Nextbillionai::Models::Geofence::ConsolePreviewResponse::Data
        ) -> Nextbillionai::Models::Geofence::ConsolePreviewResponse::Data

        attr_reader message: String?

        def message=: (String) -> String

        def initialize: (
          ?data: Nextbillionai::Models::Geofence::ConsolePreviewResponse::Data,
          ?message: String
        ) -> void

        def to_hash: -> {
          data: Nextbillionai::Models::Geofence::ConsolePreviewResponse::Data,
          message: String
        }

        type data = { geojson: Nextbillionai::Geofence::PolygonGeojson }

        class Data < Nextbillionai::Internal::Type::BaseModel
          attr_reader geojson: Nextbillionai::Geofence::PolygonGeojson?

          def geojson=: (
            Nextbillionai::Geofence::PolygonGeojson
          ) -> Nextbillionai::Geofence::PolygonGeojson

          def initialize: (
            ?geojson: Nextbillionai::Geofence::PolygonGeojson
          ) -> void

          def to_hash: -> { geojson: Nextbillionai::Geofence::PolygonGeojson }
        end
      end
    end
  end
end
