module NextbillionSDK
  module Resources
    class Skynet
      class Asset
        attr_reader event: NextbillionSDK::Resources::Skynet::Asset::Event

        attr_reader location: NextbillionSDK::Resources::Skynet::Asset::Location

        def create: (
          key: String,
          ?cluster: NextbillionSDK::Models::Skynet::AssetCreateParams::cluster,
          ?attributes: top,
          ?custom_id: String,
          ?description: String,
          ?meta_data: top,
          ?name: String,
          ?tags: ::Array[String],
          ?request_options: NextbillionSDK::request_opts
        ) -> NextbillionSDK::Models::Skynet::AssetCreateResponse

        def retrieve: (
          String id,
          key: String,
          ?cluster: NextbillionSDK::Models::Skynet::AssetRetrieveParams::cluster,
          ?request_options: NextbillionSDK::request_opts
        ) -> NextbillionSDK::Models::Skynet::AssetRetrieveResponse

        def update: (
          String id,
          key: String,
          ?cluster: NextbillionSDK::Models::Skynet::AssetUpdateParams::cluster,
          ?attributes: top,
          ?description: String,
          ?meta_data: top,
          ?name: String,
          ?tags: ::Array[String],
          ?request_options: NextbillionSDK::request_opts
        ) -> NextbillionSDK::Skynet::SimpleResp

        def list: (
          key: String,
          ?cluster: NextbillionSDK::Models::Skynet::AssetListParams::cluster,
          ?include_all_of_attributes: String,
          ?include_any_of_attributes: String,
          ?pn: Integer,
          ?ps: Integer,
          ?sort: String,
          ?tags: String,
          ?request_options: NextbillionSDK::request_opts
        ) -> NextbillionSDK::Models::Skynet::AssetListResponse

        def delete: (
          String id,
          key: String,
          ?cluster: NextbillionSDK::Models::Skynet::AssetDeleteParams::cluster,
          ?request_options: NextbillionSDK::request_opts
        ) -> NextbillionSDK::Skynet::SimpleResp

        def bind: (
          String id,
          key: String,
          device_id: String,
          ?request_options: NextbillionSDK::request_opts
        ) -> NextbillionSDK::Skynet::SimpleResp

        def track: (
          String id,
          key: String,
          device_id: String,
          locations: NextbillionSDK::Skynet::AssetTrackParams::Locations,
          ?cluster: NextbillionSDK::Models::Skynet::AssetTrackParams::cluster,
          ?request_options: NextbillionSDK::request_opts
        ) -> NextbillionSDK::Skynet::SimpleResp

        def update_attributes: (
          String id,
          key: String,
          attributes: top,
          ?request_options: NextbillionSDK::request_opts
        ) -> NextbillionSDK::Skynet::SimpleResp

        def initialize: (client: NextbillionSDK::Client) -> void
      end
    end
  end
end
