module NextbillionSDK
  module Resources
    class Skynet
      class Monitor
        def create: (
          key: String,
          tags: ::Array[String],
          type: NextbillionSDK::Models::Skynet::MonitorCreateParams::type_,
          ?cluster: NextbillionSDK::Models::Skynet::MonitorCreateParams::cluster,
          ?custom_id: String,
          ?description: String,
          ?geofence_config: NextbillionSDK::Skynet::MonitorCreateParams::GeofenceConfig,
          ?geofence_ids: ::Array[String],
          ?idle_config: NextbillionSDK::Skynet::MonitorCreateParams::IdleConfig,
          ?match_filter: NextbillionSDK::Skynet::MonitorCreateParams::MatchFilter,
          ?meta_data: top,
          ?name: String,
          ?speeding_config: NextbillionSDK::Skynet::MonitorCreateParams::SpeedingConfig,
          ?request_options: NextbillionSDK::request_opts
        ) -> NextbillionSDK::Models::Skynet::MonitorCreateResponse

        def retrieve: (
          String id,
          key: String,
          ?request_options: NextbillionSDK::request_opts
        ) -> NextbillionSDK::Models::Skynet::MonitorRetrieveResponse

        def update: (
          String id,
          key: String,
          ?description: String,
          ?geofence_config: NextbillionSDK::Skynet::MonitorUpdateParams::GeofenceConfig,
          ?geofence_ids: ::Array[String],
          ?idle_config: NextbillionSDK::Skynet::MonitorUpdateParams::IdleConfig,
          ?match_filter: NextbillionSDK::Skynet::MonitorUpdateParams::MatchFilter,
          ?meta_data: top,
          ?name: String,
          ?speeding_config: NextbillionSDK::Skynet::MonitorUpdateParams::SpeedingConfig,
          ?tags: ::Array[String],
          ?type: NextbillionSDK::Models::Skynet::MonitorUpdateParams::type_,
          ?request_options: NextbillionSDK::request_opts
        ) -> NextbillionSDK::Skynet::SimpleResp

        def list: (
          key: String,
          ?cluster: NextbillionSDK::Models::Skynet::MonitorListParams::cluster,
          ?pn: Integer,
          ?ps: Integer,
          ?sort: String,
          ?tags: String,
          ?request_options: NextbillionSDK::request_opts
        ) -> NextbillionSDK::Models::Skynet::MonitorListResponse

        def delete: (
          String id,
          key: String,
          ?request_options: NextbillionSDK::request_opts
        ) -> NextbillionSDK::Skynet::SimpleResp

        def initialize: (client: NextbillionSDK::Client) -> void
      end
    end
  end
end
