module NextbillionSDK
  module Resources
    class Skynet
      class NamespacedApikeys
        def create: (
          key: String,
          namespace: String,
          ?request_options: NextbillionSDK::request_opts
        ) -> NextbillionSDK::Models::Skynet::NamespacedApikeyCreateResponse

        def delete: (
          key: String,
          key_to_delete: String,
          namespace: String,
          ?request_options: NextbillionSDK::request_opts
        ) -> NextbillionSDK::Models::Skynet::NamespacedApikeyDeleteResponse

        def initialize: (client: NextbillionSDK::Client) -> void
      end
    end
  end
end
