module NextbillionSDK
  module Models
    type batch_retrieve_params =
      { key: String, track_id: String }
      & NextbillionSDK::Internal::Type::request_parameters

    class BatchRetrieveParams < NextbillionSDK::Internal::Type::BaseModel
      extend NextbillionSDK::Internal::Type::RequestParameters::Converter
      include NextbillionSDK::Internal::Type::RequestParameters

      attr_accessor key: String

      attr_accessor track_id: String

      def initialize: (
        key: String,
        track_id: String,
        ?request_options: NextbillionSDK::request_opts
      ) -> void

      def to_hash: -> {
        key: String,
        track_id: String,
        request_options: NextbillionSDK::RequestOptions
      }
    end
  end
end
