module NextbillionSDK
  module Models
    type contacts =
      {
        email: ::Array[NextbillionSDK::ContactObject],
        fax: ::Array[NextbillionSDK::ContactObject],
        mobile: ::Array[NextbillionSDK::ContactObject],
        phone: ::Array[NextbillionSDK::ContactObject],
        toll_free: ::Array[NextbillionSDK::ContactObject],
        www: ::Array[NextbillionSDK::ContactObject]
      }

    class Contacts < NextbillionSDK::Internal::Type::BaseModel
      attr_reader email: ::Array[NextbillionSDK::ContactObject]?

      def email=: (
        ::Array[NextbillionSDK::ContactObject]
      ) -> ::Array[NextbillionSDK::ContactObject]

      attr_reader fax: ::Array[NextbillionSDK::ContactObject]?

      def fax=: (
        ::Array[NextbillionSDK::ContactObject]
      ) -> ::Array[NextbillionSDK::ContactObject]

      attr_reader mobile: ::Array[NextbillionSDK::ContactObject]?

      def mobile=: (
        ::Array[NextbillionSDK::ContactObject]
      ) -> ::Array[NextbillionSDK::ContactObject]

      attr_reader phone: ::Array[NextbillionSDK::ContactObject]?

      def phone=: (
        ::Array[NextbillionSDK::ContactObject]
      ) -> ::Array[NextbillionSDK::ContactObject]

      attr_reader toll_free: ::Array[NextbillionSDK::ContactObject]?

      def toll_free=: (
        ::Array[NextbillionSDK::ContactObject]
      ) -> ::Array[NextbillionSDK::ContactObject]

      attr_reader www: ::Array[NextbillionSDK::ContactObject]?

      def www=: (
        ::Array[NextbillionSDK::ContactObject]
      ) -> ::Array[NextbillionSDK::ContactObject]

      def initialize: (
        ?email: ::Array[NextbillionSDK::ContactObject],
        ?fax: ::Array[NextbillionSDK::ContactObject],
        ?mobile: ::Array[NextbillionSDK::ContactObject],
        ?phone: ::Array[NextbillionSDK::ContactObject],
        ?toll_free: ::Array[NextbillionSDK::ContactObject],
        ?www: ::Array[NextbillionSDK::ContactObject]
      ) -> void

      def to_hash: -> {
        email: ::Array[NextbillionSDK::ContactObject],
        fax: ::Array[NextbillionSDK::ContactObject],
        mobile: ::Array[NextbillionSDK::ContactObject],
        phone: ::Array[NextbillionSDK::ContactObject],
        toll_free: ::Array[NextbillionSDK::ContactObject],
        www: ::Array[NextbillionSDK::ContactObject]
      }
    end
  end
end
