module NextbillionSDK
  module Models
    type geofence_create_params =
      { key: String } & NextbillionSDK::Internal::Type::request_parameters

    class GeofenceCreateParams < NextbillionSDK::Models::GeofenceEntityCreate
      extend NextbillionSDK::Internal::Type::RequestParameters::Converter
      include NextbillionSDK::Internal::Type::RequestParameters

      def key: -> String

      def key=: (String _) -> String

      def initialize: (
        key: String,
        ?request_options: NextbillionSDK::request_opts
      ) -> void

      def to_hash: -> {
        key: String,
        request_options: NextbillionSDK::RequestOptions
      }
    end
  end
end
