module NextbillionSDK
  module Models
    type geofence_list_response =
      {
        data: NextbillionSDK::Models::GeofenceListResponse::Data,
        status: String
      }

    class GeofenceListResponse < NextbillionSDK::Internal::Type::BaseModel
      attr_reader data: NextbillionSDK::Models::GeofenceListResponse::Data?

      def data=: (
        NextbillionSDK::Models::GeofenceListResponse::Data
      ) -> NextbillionSDK::Models::GeofenceListResponse::Data

      attr_reader status: String?

      def status=: (String) -> String

      def initialize: (
        ?data: NextbillionSDK::Models::GeofenceListResponse::Data,
        ?status: String
      ) -> void

      def to_hash: -> {
        data: NextbillionSDK::Models::GeofenceListResponse::Data,
        status: String
      }

      type data =
        {
          list: ::Array[NextbillionSDK::GeofenceAPI],
          page: NextbillionSDK::Skynet::Pagination
        }

      class Data < NextbillionSDK::Internal::Type::BaseModel
        attr_reader list: ::Array[NextbillionSDK::GeofenceAPI]?

        def list=: (
          ::Array[NextbillionSDK::GeofenceAPI]
        ) -> ::Array[NextbillionSDK::GeofenceAPI]

        attr_reader page: NextbillionSDK::Skynet::Pagination?

        def page=: (
          NextbillionSDK::Skynet::Pagination
        ) -> NextbillionSDK::Skynet::Pagination

        def initialize: (
          ?list: ::Array[NextbillionSDK::GeofenceAPI],
          ?page: NextbillionSDK::Skynet::Pagination
        ) -> void

        def to_hash: -> {
          list: ::Array[NextbillionSDK::GeofenceAPI],
          page: NextbillionSDK::Skynet::Pagination
        }
      end
    end
  end
end
