module NextbillionSDK
  module Models
    type geofence_create_response =
      {
        data: NextbillionSDK::Models::GeofenceCreateResponse::Data,
        status: String
      }

    class GeofenceCreateResponse < NextbillionSDK::Internal::Type::BaseModel
      attr_reader data: NextbillionSDK::Models::GeofenceCreateResponse::Data?

      def data=: (
        NextbillionSDK::Models::GeofenceCreateResponse::Data
      ) -> NextbillionSDK::Models::GeofenceCreateResponse::Data

      attr_reader status: String?

      def status=: (String) -> String

      def initialize: (
        ?data: NextbillionSDK::Models::GeofenceCreateResponse::Data,
        ?status: String
      ) -> void

      def to_hash: -> {
        data: NextbillionSDK::Models::GeofenceCreateResponse::Data,
        status: String
      }

      type data = { id: String }

      class Data < NextbillionSDK::Internal::Type::BaseModel
        attr_reader id: String?

        def id=: (String) -> String

        def initialize: (?id: String) -> void

        def to_hash: -> { id: String }
      end
    end
  end
end
