module NextbillionSDK
  module Models
    type lookup_by_id_response =
      { items: ::Array[NextbillionSDK::Models::LookupByIDResponse::Item] }

    class LookupByIDResponse < NextbillionSDK::Internal::Type::BaseModel
      attr_reader items: ::Array[NextbillionSDK::Models::LookupByIDResponse::Item]?

      def items=: (
        ::Array[NextbillionSDK::Models::LookupByIDResponse::Item]
      ) -> ::Array[NextbillionSDK::Models::LookupByIDResponse::Item]

      def initialize: (
        ?items: ::Array[NextbillionSDK::Models::LookupByIDResponse::Item]
      ) -> void

      def to_hash: -> {
        items: ::Array[NextbillionSDK::Models::LookupByIDResponse::Item]
      }

      type item =
        {
          id: String,
          access: NextbillionSDK::Access,
          address: NextbillionSDK::Address,
          categories: ::Array[NextbillionSDK::Categories],
          contacts: ::Array[NextbillionSDK::Contacts],
          map_view: NextbillionSDK::MapView,
          position: NextbillionSDK::Position,
          title: String
        }

      class Item < NextbillionSDK::Internal::Type::BaseModel
        attr_reader id: String?

        def id=: (String) -> String

        attr_reader access: NextbillionSDK::Access?

        def access=: (NextbillionSDK::Access) -> NextbillionSDK::Access

        attr_reader address: NextbillionSDK::Address?

        def address=: (NextbillionSDK::Address) -> NextbillionSDK::Address

        attr_reader categories: ::Array[NextbillionSDK::Categories]?

        def categories=: (
          ::Array[NextbillionSDK::Categories]
        ) -> ::Array[NextbillionSDK::Categories]

        attr_reader contacts: ::Array[NextbillionSDK::Contacts]?

        def contacts=: (
          ::Array[NextbillionSDK::Contacts]
        ) -> ::Array[NextbillionSDK::Contacts]

        attr_reader map_view: NextbillionSDK::MapView?

        def map_view=: (NextbillionSDK::MapView) -> NextbillionSDK::MapView

        attr_reader position: NextbillionSDK::Position?

        def position=: (NextbillionSDK::Position) -> NextbillionSDK::Position

        attr_reader title: String?

        def title=: (String) -> String

        def initialize: (
          ?id: String,
          ?access: NextbillionSDK::Access,
          ?address: NextbillionSDK::Address,
          ?categories: ::Array[NextbillionSDK::Categories],
          ?contacts: ::Array[NextbillionSDK::Contacts],
          ?map_view: NextbillionSDK::MapView,
          ?position: NextbillionSDK::Position,
          ?title: String
        ) -> void

        def to_hash: -> {
          id: String,
          access: NextbillionSDK::Access,
          address: NextbillionSDK::Address,
          categories: ::Array[NextbillionSDK::Categories],
          contacts: ::Array[NextbillionSDK::Contacts],
          map_view: NextbillionSDK::MapView,
          position: NextbillionSDK::Position,
          title: String
        }
      end
    end
  end
end
