module NextbillionSDK
  module Models
    type mdm_get_distance_matrix_status_response =
      {
        code: NextbillionSDK::Models::MdmGetDistanceMatrixStatusResponse::code,
        output_addr: String,
        result_link: String,
        status: String
      }

    class MdmGetDistanceMatrixStatusResponse < NextbillionSDK::Internal::Type::BaseModel
      attr_reader code: NextbillionSDK::Models::MdmGetDistanceMatrixStatusResponse::code?

      def code=: (
        NextbillionSDK::Models::MdmGetDistanceMatrixStatusResponse::code
      ) -> NextbillionSDK::Models::MdmGetDistanceMatrixStatusResponse::code

      attr_reader output_addr: String?

      def output_addr=: (String) -> String

      attr_reader result_link: String?

      def result_link=: (String) -> String

      attr_reader status: String?

      def status=: (String) -> String

      def initialize: (
        ?code: NextbillionSDK::Models::MdmGetDistanceMatrixStatusResponse::code,
        ?output_addr: String,
        ?result_link: String,
        ?status: String
      ) -> void

      def to_hash: -> {
        code: NextbillionSDK::Models::MdmGetDistanceMatrixStatusResponse::code,
        output_addr: String,
        result_link: String,
        status: String
      }

      type code = :Ok | :Processing | :Failed

      module Code
        extend NextbillionSDK::Internal::Type::Enum

        OK: :Ok
        PROCESSING: :Processing
        FAILED: :Failed

        def self?.values: -> ::Array[NextbillionSDK::Models::MdmGetDistanceMatrixStatusResponse::code]
      end
    end
  end
end
