module NextbillionSDK
  module Models
    type optimization_re_optimize_params =
      {
        key: String,
        existing_request_id: String,
        job_changes: NextbillionSDK::OptimizationReOptimizeParams::JobChanges,
        locations: ::Array[String],
        shipment_changes: NextbillionSDK::OptimizationReOptimizeParams::ShipmentChanges,
        vehicle_changes: NextbillionSDK::OptimizationReOptimizeParams::VehicleChanges
      }
      & NextbillionSDK::Internal::Type::request_parameters

    class OptimizationReOptimizeParams < NextbillionSDK::Internal::Type::BaseModel
      extend NextbillionSDK::Internal::Type::RequestParameters::Converter
      include NextbillionSDK::Internal::Type::RequestParameters

      attr_accessor key: String

      attr_accessor existing_request_id: String

      attr_reader job_changes: NextbillionSDK::OptimizationReOptimizeParams::JobChanges?

      def job_changes=: (
        NextbillionSDK::OptimizationReOptimizeParams::JobChanges
      ) -> NextbillionSDK::OptimizationReOptimizeParams::JobChanges

      attr_reader locations: ::Array[String]?

      def locations=: (::Array[String]) -> ::Array[String]

      attr_reader shipment_changes: NextbillionSDK::OptimizationReOptimizeParams::ShipmentChanges?

      def shipment_changes=: (
        NextbillionSDK::OptimizationReOptimizeParams::ShipmentChanges
      ) -> NextbillionSDK::OptimizationReOptimizeParams::ShipmentChanges

      attr_reader vehicle_changes: NextbillionSDK::OptimizationReOptimizeParams::VehicleChanges?

      def vehicle_changes=: (
        NextbillionSDK::OptimizationReOptimizeParams::VehicleChanges
      ) -> NextbillionSDK::OptimizationReOptimizeParams::VehicleChanges

      def initialize: (
        key: String,
        existing_request_id: String,
        ?job_changes: NextbillionSDK::OptimizationReOptimizeParams::JobChanges,
        ?locations: ::Array[String],
        ?shipment_changes: NextbillionSDK::OptimizationReOptimizeParams::ShipmentChanges,
        ?vehicle_changes: NextbillionSDK::OptimizationReOptimizeParams::VehicleChanges,
        ?request_options: NextbillionSDK::request_opts
      ) -> void

      def to_hash: -> {
        key: String,
        existing_request_id: String,
        job_changes: NextbillionSDK::OptimizationReOptimizeParams::JobChanges,
        locations: ::Array[String],
        shipment_changes: NextbillionSDK::OptimizationReOptimizeParams::ShipmentChanges,
        vehicle_changes: NextbillionSDK::OptimizationReOptimizeParams::VehicleChanges,
        request_options: NextbillionSDK::RequestOptions
      }

      type job_changes =
        {
          add: ::Array[NextbillionSDK::Optimization::Job],
          modify: ::Array[NextbillionSDK::Optimization::Job],
          remove: ::Array[String]
        }

      class JobChanges < NextbillionSDK::Internal::Type::BaseModel
        attr_reader add: ::Array[NextbillionSDK::Optimization::Job]?

        def add=: (
          ::Array[NextbillionSDK::Optimization::Job]
        ) -> ::Array[NextbillionSDK::Optimization::Job]

        attr_reader modify: ::Array[NextbillionSDK::Optimization::Job]?

        def modify=: (
          ::Array[NextbillionSDK::Optimization::Job]
        ) -> ::Array[NextbillionSDK::Optimization::Job]

        attr_reader remove: ::Array[String]?

        def remove=: (::Array[String]) -> ::Array[String]

        def initialize: (
          ?add: ::Array[NextbillionSDK::Optimization::Job],
          ?modify: ::Array[NextbillionSDK::Optimization::Job],
          ?remove: ::Array[String]
        ) -> void

        def to_hash: -> {
          add: ::Array[NextbillionSDK::Optimization::Job],
          modify: ::Array[NextbillionSDK::Optimization::Job],
          remove: ::Array[String]
        }
      end

      type shipment_changes =
        {
          add: ::Array[NextbillionSDK::Optimization::Shipment],
          modify: ::Array[NextbillionSDK::Optimization::Shipment],
          remove: ::Array[String]
        }

      class ShipmentChanges < NextbillionSDK::Internal::Type::BaseModel
        attr_reader add: ::Array[NextbillionSDK::Optimization::Shipment]?

        def add=: (
          ::Array[NextbillionSDK::Optimization::Shipment]
        ) -> ::Array[NextbillionSDK::Optimization::Shipment]

        attr_reader modify: ::Array[NextbillionSDK::Optimization::Shipment]?

        def modify=: (
          ::Array[NextbillionSDK::Optimization::Shipment]
        ) -> ::Array[NextbillionSDK::Optimization::Shipment]

        attr_reader remove: ::Array[String]?

        def remove=: (::Array[String]) -> ::Array[String]

        def initialize: (
          ?add: ::Array[NextbillionSDK::Optimization::Shipment],
          ?modify: ::Array[NextbillionSDK::Optimization::Shipment],
          ?remove: ::Array[String]
        ) -> void

        def to_hash: -> {
          add: ::Array[NextbillionSDK::Optimization::Shipment],
          modify: ::Array[NextbillionSDK::Optimization::Shipment],
          remove: ::Array[String]
        }
      end

      type vehicle_changes =
        {
          add: ::Array[NextbillionSDK::Optimization::Vehicle],
          modify: NextbillionSDK::Optimization::Vehicle,
          remove: ::Array[String]
        }

      class VehicleChanges < NextbillionSDK::Internal::Type::BaseModel
        attr_reader add: ::Array[NextbillionSDK::Optimization::Vehicle]?

        def add=: (
          ::Array[NextbillionSDK::Optimization::Vehicle]
        ) -> ::Array[NextbillionSDK::Optimization::Vehicle]

        attr_reader modify: NextbillionSDK::Optimization::Vehicle?

        def modify=: (
          NextbillionSDK::Optimization::Vehicle
        ) -> NextbillionSDK::Optimization::Vehicle

        attr_reader remove: ::Array[String]?

        def remove=: (::Array[String]) -> ::Array[String]

        def initialize: (
          ?add: ::Array[NextbillionSDK::Optimization::Vehicle],
          ?modify: NextbillionSDK::Optimization::Vehicle,
          ?remove: ::Array[String]
        ) -> void

        def to_hash: -> {
          add: ::Array[NextbillionSDK::Optimization::Vehicle],
          modify: NextbillionSDK::Optimization::Vehicle,
          remove: ::Array[String]
        }
      end
    end
  end
end
