module NextbillionSDK
  module Models
    type postalcode_retrieve_coordinates_params =
      {
        key: String,
        at: NextbillionSDK::PostalcodeRetrieveCoordinatesParams::At,
        country: String,
        format_: NextbillionSDK::Models::PostalcodeRetrieveCoordinatesParams::format_,
        postalcode: String
      }
      & NextbillionSDK::Internal::Type::request_parameters

    class PostalcodeRetrieveCoordinatesParams < NextbillionSDK::Internal::Type::BaseModel
      extend NextbillionSDK::Internal::Type::RequestParameters::Converter
      include NextbillionSDK::Internal::Type::RequestParameters

      attr_accessor key: String

      attr_reader at: NextbillionSDK::PostalcodeRetrieveCoordinatesParams::At?

      def at=: (
        NextbillionSDK::PostalcodeRetrieveCoordinatesParams::At
      ) -> NextbillionSDK::PostalcodeRetrieveCoordinatesParams::At

      attr_reader country: String?

      def country=: (String) -> String

      attr_reader format_: NextbillionSDK::Models::PostalcodeRetrieveCoordinatesParams::format_?

      def format_=: (
        NextbillionSDK::Models::PostalcodeRetrieveCoordinatesParams::format_
      ) -> NextbillionSDK::Models::PostalcodeRetrieveCoordinatesParams::format_

      attr_reader postalcode: String?

      def postalcode=: (String) -> String

      def initialize: (
        key: String,
        ?at: NextbillionSDK::PostalcodeRetrieveCoordinatesParams::At,
        ?country: String,
        ?format_: NextbillionSDK::Models::PostalcodeRetrieveCoordinatesParams::format_,
        ?postalcode: String,
        ?request_options: NextbillionSDK::request_opts
      ) -> void

      def to_hash: -> {
        key: String,
        at: NextbillionSDK::PostalcodeRetrieveCoordinatesParams::At,
        country: String,
        format_: NextbillionSDK::Models::PostalcodeRetrieveCoordinatesParams::format_,
        postalcode: String,
        request_options: NextbillionSDK::RequestOptions
      }

      type at = { lat: Float, lng: Float }

      class At < NextbillionSDK::Internal::Type::BaseModel
        attr_reader lat: Float?

        def lat=: (Float) -> Float

        attr_reader lng: Float?

        def lng=: (Float) -> Float

        def initialize: (?lat: Float, ?lng: Float) -> void

        def to_hash: -> { lat: Float, lng: Float }
      end

      type format_ = :geojson

      module Format
        extend NextbillionSDK::Internal::Type::Enum

        GEOJSON: :geojson

        def self?.values: -> ::Array[NextbillionSDK::Models::PostalcodeRetrieveCoordinatesParams::format_]
      end
    end
  end
end
