module NextbillionSDK
  module Models
    type post_response =
      { id: String, message: String, status: String, warnings: ::Array[String] }

    class PostResponse < NextbillionSDK::Internal::Type::BaseModel
      attr_reader id: String?

      def id=: (String) -> String

      attr_reader message: String?

      def message=: (String) -> String

      attr_reader status: String?

      def status=: (String) -> String

      attr_reader warnings: ::Array[String]?

      def warnings=: (::Array[String]) -> ::Array[String]

      def initialize: (
        ?id: String,
        ?message: String,
        ?status: String,
        ?warnings: ::Array[String]
      ) -> void

      def to_hash: -> {
        id: String,
        message: String,
        status: String,
        warnings: ::Array[String]
      }
    end
  end
end
