module NextbillionSDK
  module Models
    type restriction_list_by_bbox_params =
      {
        key: String,
        max_lat: Float,
        max_lon: Float,
        min_lat: Float,
        min_lon: Float,
        mode: ::Array[NextbillionSDK::Models::RestrictionListByBboxParams::mode],
        restriction_type: NextbillionSDK::Models::RestrictionListByBboxParams::restriction_type,
        source: NextbillionSDK::Models::RestrictionListByBboxParams::source,
        state: NextbillionSDK::Models::RestrictionListByBboxParams::state,
        status: NextbillionSDK::Models::RestrictionListByBboxParams::status,
        transform: bool
      }
      & NextbillionSDK::Internal::Type::request_parameters

    class RestrictionListByBboxParams < NextbillionSDK::Internal::Type::BaseModel
      extend NextbillionSDK::Internal::Type::RequestParameters::Converter
      include NextbillionSDK::Internal::Type::RequestParameters

      attr_accessor key: String

      attr_accessor max_lat: Float

      attr_accessor max_lon: Float

      attr_accessor min_lat: Float

      attr_accessor min_lon: Float

      attr_reader mode: ::Array[NextbillionSDK::Models::RestrictionListByBboxParams::mode]?

      def mode=: (
        ::Array[NextbillionSDK::Models::RestrictionListByBboxParams::mode]
      ) -> ::Array[NextbillionSDK::Models::RestrictionListByBboxParams::mode]

      attr_reader restriction_type: NextbillionSDK::Models::RestrictionListByBboxParams::restriction_type?

      def restriction_type=: (
        NextbillionSDK::Models::RestrictionListByBboxParams::restriction_type
      ) -> NextbillionSDK::Models::RestrictionListByBboxParams::restriction_type

      attr_reader source: NextbillionSDK::Models::RestrictionListByBboxParams::source?

      def source=: (
        NextbillionSDK::Models::RestrictionListByBboxParams::source
      ) -> NextbillionSDK::Models::RestrictionListByBboxParams::source

      attr_reader state: NextbillionSDK::Models::RestrictionListByBboxParams::state?

      def state=: (
        NextbillionSDK::Models::RestrictionListByBboxParams::state
      ) -> NextbillionSDK::Models::RestrictionListByBboxParams::state

      attr_reader status: NextbillionSDK::Models::RestrictionListByBboxParams::status?

      def status=: (
        NextbillionSDK::Models::RestrictionListByBboxParams::status
      ) -> NextbillionSDK::Models::RestrictionListByBboxParams::status

      attr_reader transform: bool?

      def transform=: (bool) -> bool

      def initialize: (
        key: String,
        max_lat: Float,
        max_lon: Float,
        min_lat: Float,
        min_lon: Float,
        ?mode: ::Array[NextbillionSDK::Models::RestrictionListByBboxParams::mode],
        ?restriction_type: NextbillionSDK::Models::RestrictionListByBboxParams::restriction_type,
        ?source: NextbillionSDK::Models::RestrictionListByBboxParams::source,
        ?state: NextbillionSDK::Models::RestrictionListByBboxParams::state,
        ?status: NextbillionSDK::Models::RestrictionListByBboxParams::status,
        ?transform: bool,
        ?request_options: NextbillionSDK::request_opts
      ) -> void

      def to_hash: -> {
        key: String,
        max_lat: Float,
        max_lon: Float,
        min_lat: Float,
        min_lon: Float,
        mode: ::Array[NextbillionSDK::Models::RestrictionListByBboxParams::mode],
        restriction_type: NextbillionSDK::Models::RestrictionListByBboxParams::restriction_type,
        source: NextbillionSDK::Models::RestrictionListByBboxParams::source,
        state: NextbillionSDK::Models::RestrictionListByBboxParams::state,
        status: NextbillionSDK::Models::RestrictionListByBboxParams::status,
        transform: bool,
        request_options: NextbillionSDK::RequestOptions
      }

      type mode = :"0w" | :"2w" | :"3w" | :"4w" | :"6w"

      module Mode
        extend NextbillionSDK::Internal::Type::Enum

        MODE_0W: :"0w"
        MODE_2W: :"2w"
        MODE_3W: :"3w"
        MODE_4W: :"4w"
        MODE_6W: :"6w"

        def self?.values: -> ::Array[NextbillionSDK::Models::RestrictionListByBboxParams::mode]
      end

      type restriction_type =
        :turn | :parking | :fixedspeed | :maxspeed | :closure | :truck

      module RestrictionType
        extend NextbillionSDK::Internal::Type::Enum

        TURN: :turn
        PARKING: :parking
        FIXEDSPEED: :fixedspeed
        MAXSPEED: :maxspeed
        CLOSURE: :closure
        TRUCK: :truck

        def self?.values: -> ::Array[NextbillionSDK::Models::RestrictionListByBboxParams::restriction_type]
      end

      type source = :rrt | :pbf

      module Source
        extend NextbillionSDK::Internal::Type::Enum

        RRT: :rrt
        PBF: :pbf

        def self?.values: -> ::Array[NextbillionSDK::Models::RestrictionListByBboxParams::source]
      end

      type state = :enabled | :disabled | :deleted

      module State
        extend NextbillionSDK::Internal::Type::Enum

        ENABLED: :enabled
        DISABLED: :disabled
        DELETED: :deleted

        def self?.values: -> ::Array[NextbillionSDK::Models::RestrictionListByBboxParams::state]
      end

      type status = :active | :inactive

      module Status
        extend NextbillionSDK::Internal::Type::Enum

        ACTIVE: :active
        INACTIVE: :inactive

        def self?.values: -> ::Array[NextbillionSDK::Models::RestrictionListByBboxParams::status]
      end
    end
  end
end
