module NextbillionSDK
  module Models
    type restriction_update_params =
      { key: String, latlon: bool }
      & NextbillionSDK::Internal::Type::request_parameters

    class RestrictionUpdateParams < NextbillionSDK::Models::RichGroupRequest
      extend NextbillionSDK::Internal::Type::RequestParameters::Converter
      include NextbillionSDK::Internal::Type::RequestParameters

      def key: -> String

      def key=: (String _) -> String

      def latlon: -> bool?

      def latlon=: (bool _) -> bool

      def initialize: (
        key: String,
        ?latlon: bool,
        ?request_options: NextbillionSDK::request_opts
      ) -> void

      def to_hash: -> {
        key: String,
        latlon: bool,
        request_options: NextbillionSDK::RequestOptions
      }
    end
  end
end
