module NextbillionSDK
  module Models
    type skynet_subscribe_params =
      {
        action: NextbillionSDK::Models::SkynetSubscribeParams::action,
        id: String,
        params: NextbillionSDK::SkynetSubscribeParams::Params
      }
      & NextbillionSDK::Internal::Type::request_parameters

    class SkynetSubscribeParams < NextbillionSDK::Internal::Type::BaseModel
      extend NextbillionSDK::Internal::Type::RequestParameters::Converter
      include NextbillionSDK::Internal::Type::RequestParameters

      attr_accessor action: NextbillionSDK::Models::SkynetSubscribeParams::action

      attr_reader id: String?

      def id=: (String) -> String

      attr_reader params: NextbillionSDK::SkynetSubscribeParams::Params?

      def params=: (
        NextbillionSDK::SkynetSubscribeParams::Params
      ) -> NextbillionSDK::SkynetSubscribeParams::Params

      def initialize: (
        action: NextbillionSDK::Models::SkynetSubscribeParams::action,
        ?id: String,
        ?params: NextbillionSDK::SkynetSubscribeParams::Params,
        ?request_options: NextbillionSDK::request_opts
      ) -> void

      def to_hash: -> {
        action: NextbillionSDK::Models::SkynetSubscribeParams::action,
        id: String,
        params: NextbillionSDK::SkynetSubscribeParams::Params,
        request_options: NextbillionSDK::RequestOptions
      }

      type action = :"`TRIP_SUBSCRIBE`" | :"`TRIP_UNSUBSCRIBE`" | :"`HEARTBEAT`"

      module Action
        extend NextbillionSDK::Internal::Type::Enum

        TRIP_SUBSCRIBE: :"`TRIP_SUBSCRIBE`"
        TRIP_UNSUBSCRIBE: :"`TRIP_UNSUBSCRIBE`"
        HEARTBEAT: :"`HEARTBEAT`"

        def self?.values: -> ::Array[NextbillionSDK::Models::SkynetSubscribeParams::action]
      end

      type params = { id: String }

      class Params < NextbillionSDK::Internal::Type::BaseModel
        attr_accessor id: String

        def initialize: (id: String) -> void

        def to_hash: -> { id: String }
      end
    end
  end
end
