module Nextbillionai
  module Models
    module DistanceMatrix
      type json_create_params =
        {  } & Nextbillionai::Internal::Type::request_parameters

      class JsonCreateParams < Nextbillionai::Internal::Type::BaseModel
        extend Nextbillionai::Internal::Type::RequestParameters::Converter
        include Nextbillionai::Internal::Type::RequestParameters

        def initialize: (?request_options: Nextbillionai::request_opts) -> void

        def to_hash: -> { request_options: Nextbillionai::RequestOptions }
      end
    end
  end
end
