module Nextbillionai
  module Resources
    class Geofence
      class Batch
        def create: (
          key: String,
          ?geofences: ::Array[Nextbillionai::GeofenceEntityCreate],
          ?request_options: Nextbillionai::request_opts
        ) -> Nextbillionai::Models::Geofence::BatchCreateResponse

        def list: (
          ids: String,
          key: String,
          ?request_options: Nextbillionai::request_opts
        ) -> Nextbillionai::Models::Geofence::BatchListResponse

        def delete: (
          key: String,
          ?ids: ::Array[String],
          ?request_options: Nextbillionai::request_opts
        ) -> Nextbillionai::Skynet::SimpleResp

        def initialize: (client: Nextbillionai::Client) -> void
      end
    end
  end
end
