module Nextbillionai
  module Resources
    class Geofence
      class Console
        def preview: (
          type: Nextbillionai::Models::GeofenceEntityCreate::type_,
          ?circle: Nextbillionai::GeofenceEntityCreate::Circle,
          ?custom_id: String,
          ?isochrone: Nextbillionai::GeofenceEntityCreate::Isochrone,
          ?meta_data: top,
          ?name: String,
          ?polygon: Nextbillionai::GeofenceEntityCreate::Polygon,
          ?tags: ::Array[String],
          ?request_options: Nextbillionai::request_opts
        ) -> Nextbillionai::Models::Geofence::ConsolePreviewResponse

        def search: (
          query: String,
          ?request_options: Nextbillionai::request_opts
        ) -> Nextbillionai::Models::Geofence::ConsoleSearchResponse

        def initialize: (client: Nextbillionai::Client) -> void
      end
    end
  end
end
