module Nextbillionai
  class Client < Nextbillionai::Internal::Transport::BaseClient
    DEFAULT_MAX_RETRIES: 2

    DEFAULT_TIMEOUT_IN_SECONDS: Float

    DEFAULT_INITIAL_RETRY_DELAY: Float

    DEFAULT_MAX_RETRY_DELAY: Float

    attr_reader api_key: String

    attr_reader fleetify: Nextbillionai::Resources::Fleetify

    attr_reader skynet: Nextbillionai::Resources::Skynet

    attr_reader geocode: Nextbillionai::Resources::Geocode

    attr_reader optimization: Nextbillionai::Resources::Optimization

    attr_reader geofence: Nextbillionai::Resources::Geofence

    attr_reader discover: Nextbillionai::Resources::Discover

    attr_reader browse: Nextbillionai::Resources::Browse

    attr_reader mdm: Nextbillionai::Resources::Mdm

    attr_reader isochrone: Nextbillionai::Resources::Isochrone

    attr_reader restrictions: Nextbillionai::Resources::Restrictions

    attr_reader restrictions_items: Nextbillionai::Resources::RestrictionsItems

    attr_reader distance_matrix: Nextbillionai::Resources::DistanceMatrix

    attr_reader autocomplete: Nextbillionai::Resources::Autocomplete

    attr_reader navigation: Nextbillionai::Resources::Navigation

    attr_reader map: Nextbillionai::Resources::Map

    attr_reader autosuggest: Nextbillionai::Resources::Autosuggest

    attr_reader directions: Nextbillionai::Resources::Directions

    attr_reader batch: Nextbillionai::Resources::Batch

    attr_reader multigeocode: Nextbillionai::Resources::Multigeocode

    attr_reader revgeocode: Nextbillionai::Resources::Revgeocode

    attr_reader route_report: Nextbillionai::Resources::RouteReport

    attr_reader snap_to_roads: Nextbillionai::Resources::SnapToRoads

    attr_reader postalcode: Nextbillionai::Resources::Postalcode

    attr_reader lookup: Nextbillionai::Resources::Lookup

    attr_reader areas: Nextbillionai::Resources::Areas

    private def auth_query: -> ::Hash[String, String]

    def initialize: (
      ?api_key: String?,
      ?base_url: String?,
      ?max_retries: Integer,
      ?timeout: Float,
      ?initial_retry_delay: Float,
      ?max_retry_delay: Float
    ) -> void
  end
end
