module Nextbillionai
  module Internal
    extend Nextbillionai::Internal::Util::SorbetRuntimeSupport

    type file_input =
      Pathname | StringIO | IO | String | Nextbillionai::FilePart

    OMIT: Object
  end
end
