module Nextbillionai
  class Access = Nextbillionai::Models::Access

  class Address = Nextbillionai::Models::Address

  class AreaListParams = Nextbillionai::Models::AreaListParams

  class AutocompleteSuggestParams = Nextbillionai::Models::AutocompleteSuggestParams

  class AutosuggestSuggestParams = Nextbillionai::Models::AutosuggestSuggestParams

  class BatchCreateParams = Nextbillionai::Models::BatchCreateParams

  class BatchRetrieveParams = Nextbillionai::Models::BatchRetrieveParams

  class BrowseSearchParams = Nextbillionai::Models::BrowseSearchParams

  class Categories = Nextbillionai::Models::Categories

  class ContactObject = Nextbillionai::Models::ContactObject

  class Contacts = Nextbillionai::Models::Contacts

  class DirectionComputeRouteParams = Nextbillionai::Models::DirectionComputeRouteParams

  class DiscoverRetrieveParams = Nextbillionai::Models::DiscoverRetrieveParams

  module DistanceMatrix = Nextbillionai::Models::DistanceMatrix

  module Fleetify = Nextbillionai::Models::Fleetify

  class GeocodeBatchCreateParams = Nextbillionai::Models::GeocodeBatchCreateParams

  class GeocodeRetrieveParams = Nextbillionai::Models::GeocodeRetrieveParams

  class GeocodeStructuredRetrieveParams = Nextbillionai::Models::GeocodeStructuredRetrieveParams

  module Geofence = Nextbillionai::Models::Geofence

  class GeofenceAPI = Nextbillionai::Models::GeofenceAPI

  class GeofenceContainsParams = Nextbillionai::Models::GeofenceContainsParams

  class GeofenceCreateParams = Nextbillionai::Models::GeofenceCreateParams

  class GeofenceDeleteParams = Nextbillionai::Models::GeofenceDeleteParams

  class GeofenceEntityCreate = Nextbillionai::Models::GeofenceEntityCreate

  class GeofenceListParams = Nextbillionai::Models::GeofenceListParams

  class GeofenceRetrieveParams = Nextbillionai::Models::GeofenceRetrieveParams

  class GeofenceUpdateParams = Nextbillionai::Models::GeofenceUpdateParams

  class IsochroneComputeParams = Nextbillionai::Models::IsochroneComputeParams

  class LookupByIDParams = Nextbillionai::Models::LookupByIDParams

  class MapCreateSegmentParams = Nextbillionai::Models::MapCreateSegmentParams

  class MapView = Nextbillionai::Models::MapView

  class MdmCreateDistanceMatrixParams = Nextbillionai::Models::MdmCreateDistanceMatrixParams

  class MdmGetDistanceMatrixStatusParams = Nextbillionai::Models::MdmGetDistanceMatrixStatusParams

  module Multigeocode = Nextbillionai::Models::Multigeocode

  class MultigeocodeSearchParams = Nextbillionai::Models::MultigeocodeSearchParams

  class NavigationRetrieveRouteParams = Nextbillionai::Models::NavigationRetrieveRouteParams

  module Optimization = Nextbillionai::Models::Optimization

  class OptimizationComputeParams = Nextbillionai::Models::OptimizationComputeParams

  class OptimizationReOptimizeParams = Nextbillionai::Models::OptimizationReOptimizeParams

  class Position = Nextbillionai::Models::Position

  class PostalcodeRetrieveCoordinatesParams = Nextbillionai::Models::PostalcodeRetrieveCoordinatesParams

  class PostResponse = Nextbillionai::Models::PostResponse

  class RestrictionCreateParams = Nextbillionai::Models::RestrictionCreateParams

  class RestrictionDeleteParams = Nextbillionai::Models::RestrictionDeleteParams

  class RestrictionListByBboxParams = Nextbillionai::Models::RestrictionListByBboxParams

  class RestrictionListParams = Nextbillionai::Models::RestrictionListParams

  class RestrictionRetrieveParams = Nextbillionai::Models::RestrictionRetrieveParams

  class RestrictionSetStateParams = Nextbillionai::Models::RestrictionSetStateParams

  class RestrictionsItemListParams = Nextbillionai::Models::RestrictionsItemListParams

  class RestrictionUpdateParams = Nextbillionai::Models::RestrictionUpdateParams

  class RevgeocodeRetrieveParams = Nextbillionai::Models::RevgeocodeRetrieveParams

  class RichGroupRequest = Nextbillionai::Models::RichGroupRequest

  class RichGroupResponse = Nextbillionai::Models::RichGroupResponse

  class RouteReportCreateParams = Nextbillionai::Models::RouteReportCreateParams

  module Skynet = Nextbillionai::Models::Skynet

  class SkynetSubscribeParams = Nextbillionai::Models::SkynetSubscribeParams

  class SnapToRoadSnapParams = Nextbillionai::Models::SnapToRoadSnapParams
end
