module NextbillionSDK
  module Resources
    class Optimization
      class V2
        def retrieve_result: (
          id: String,
          key: String,
          ?request_options: NextbillionSDK::request_opts
        ) -> NextbillionSDK::Models::Optimization::V2RetrieveResultResponse

        def submit: (
          key: String,
          locations: NextbillionSDK::Optimization::V2SubmitParams::Locations,
          vehicles: ::Array[NextbillionSDK::Optimization::Vehicle],
          ?cost_matrix: ::Array[::Array[Integer]],
          ?depots: ::Array[NextbillionSDK::Optimization::V2SubmitParams::Depot],
          ?description: String,
          ?distance_matrix: ::Array[::Array[Integer]],
          ?duration_matrix: ::Array[::Array[Integer]],
          ?existing_solution_id: String,
          ?jobs: ::Array[NextbillionSDK::Optimization::Job],
          ?options: NextbillionSDK::Optimization::V2SubmitParams::Options,
          ?relations: ::Array[NextbillionSDK::Optimization::V2SubmitParams::Relation],
          ?shipments: ::Array[NextbillionSDK::Optimization::Shipment],
          ?solution: ::Array[NextbillionSDK::Optimization::V2SubmitParams::Solution],
          ?unassigned: NextbillionSDK::Optimization::V2SubmitParams::Unassigned,
          ?zones: ::Array[NextbillionSDK::Optimization::V2SubmitParams::Zone],
          ?request_options: NextbillionSDK::request_opts
        ) -> NextbillionSDK::PostResponse

        def initialize: (client: NextbillionSDK::Client) -> void
      end
    end
  end
end
