module NextbillionSDK
  module Resources
    class Skynet
      class Asset
        class Location
          def list: (
            String id,
            key: String,
            ?cluster: NextbillionSDK::Models::Skynet::Asset::LocationListParams::cluster,
            ?correction: String,
            ?end_time: Integer,
            ?geometry_type: NextbillionSDK::Models::Skynet::Asset::LocationListParams::geometry_type,
            ?pn: Integer,
            ?ps: Integer,
            ?start_time: Integer,
            ?request_options: NextbillionSDK::request_opts
          ) -> NextbillionSDK::Models::Skynet::Asset::LocationListResponse

          def get_last: (
            String id,
            key: String,
            ?cluster: NextbillionSDK::Models::Skynet::Asset::LocationGetLastParams::cluster,
            ?request_options: NextbillionSDK::request_opts
          ) -> NextbillionSDK::Models::Skynet::Asset::LocationGetLastResponse

          def initialize: (client: NextbillionSDK::Client) -> void
        end
      end
    end
  end
end
