module NextbillionSDK
  module Resources
    class Batch
      def create: (
        key: String,
        ?requests: ::Array[NextbillionSDK::BatchCreateParams::Request],
        ?request_options: NextbillionSDK::request_opts
      ) -> NextbillionSDK::Models::BatchCreateResponse

      def retrieve: (
        key: String,
        track_id: String,
        ?request_options: NextbillionSDK::request_opts
      ) -> NextbillionSDK::Models::BatchRetrieveResponse

      def initialize: (client: NextbillionSDK::Client) -> void
    end
  end
end
