module NextbillionSDK
  module Resources
    class Distancematrix
      attr_reader json: NextbillionSDK::Resources::Distancematrix::Json

      def initialize: (client: NextbillionSDK::Client) -> void
    end
  end
end
