module NextbillionSDK
  module Resources
    class Isochrone
      def compute: (
        contours_meters: Integer,
        contours_minutes: Integer,
        coordinates: String,
        key: String,
        ?contours_colors: String,
        ?denoise: Float,
        ?departure_time: Integer,
        ?generalize: Float,
        ?mode: NextbillionSDK::Models::IsochroneComputeParams::mode,
        ?polygons: bool,
        ?request_options: NextbillionSDK::request_opts
      ) -> NextbillionSDK::Models::IsochroneComputeResponse

      def initialize: (client: NextbillionSDK::Client) -> void
    end
  end
end
