module NextbillionSDK
  module Resources
    class Map
      def create_segment: (
        ?request_options: NextbillionSDK::request_opts
      ) -> nil

      def initialize: (client: NextbillionSDK::Client) -> void
    end
  end
end
