module NextbillionSDK
  module Resources
    class Navigation
      def retrieve_route: (
        key: String,
        ?altcount: Integer,
        ?alternatives: bool,
        ?approaches: NextbillionSDK::Models::NavigationRetrieveRouteParams::approaches,
        ?avoid: NextbillionSDK::Models::NavigationRetrieveRouteParams::avoid,
        ?bearings: String,
        ?destination: String,
        ?geometry: NextbillionSDK::Models::NavigationRetrieveRouteParams::geometry,
        ?lang: String,
        ?mode: NextbillionSDK::Models::NavigationRetrieveRouteParams::mode,
        ?origin: String,
        ?original_shape: String,
        ?original_shape_type: NextbillionSDK::Models::NavigationRetrieveRouteParams::original_shape_type,
        ?overview: NextbillionSDK::Models::NavigationRetrieveRouteParams::overview,
        ?waypoints: String,
        ?request_options: NextbillionSDK::request_opts
      ) -> NextbillionSDK::Models::NavigationRetrieveRouteResponse

      def initialize: (client: NextbillionSDK::Client) -> void
    end
  end
end
