module NextbillionSDK
  module Resources
    class Revgeocode
      def retrieve: (
        at: String,
        key: String,
        ?in_: String,
        ?lang: String,
        ?request_options: NextbillionSDK::request_opts
      ) -> NextbillionSDK::Models::RevgeocodeRetrieveResponse

      def initialize: (client: NextbillionSDK::Client) -> void
    end
  end
end
