module NextbillionSDK
  module Resources
    class RouteReport
      def create: (
        key: String,
        original_shape: String,
        original_shape_type: NextbillionSDK::Models::RouteReportCreateParams::original_shape_type,
        ?request_options: NextbillionSDK::request_opts
      ) -> NextbillionSDK::Models::RouteReportCreateResponse

      def initialize: (client: NextbillionSDK::Client) -> void
    end
  end
end
