module Nextbillionai
  module Resources
    class Skynet
      class Trip
        def retrieve: (
          String id,
          key: String,
          ?cluster: Nextbillionai::Models::Skynet::TripRetrieveParams::cluster,
          ?request_options: Nextbillionai::request_opts
        ) -> Nextbillionai::Models::Skynet::TripRetrieveResponse

        def update: (
          String id,
          key: String,
          asset_id: String,
          ?cluster: Nextbillionai::Models::Skynet::TripUpdateParams::cluster,
          ?attributes: top,
          ?description: String,
          ?meta_data: top,
          ?name: String,
          ?stops: ::Array[Nextbillionai::Skynet::TripUpdateParams::Stop],
          ?request_options: Nextbillionai::request_opts
        ) -> Nextbillionai::Skynet::SimpleResp

        def delete: (
          String id,
          key: String,
          ?cluster: Nextbillionai::Models::Skynet::TripDeleteParams::cluster,
          ?request_options: Nextbillionai::request_opts
        ) -> Nextbillionai::Skynet::SimpleResp

        def end_: (
          key: String,
          id: String,
          ?cluster: Nextbillionai::Models::Skynet::TripEndParams::cluster,
          ?request_options: Nextbillionai::request_opts
        ) -> Nextbillionai::Skynet::SimpleResp

        def get_summary: (
          String id,
          key: String,
          ?cluster: Nextbillionai::Models::Skynet::TripGetSummaryParams::cluster,
          ?request_options: Nextbillionai::request_opts
        ) -> Nextbillionai::Models::Skynet::TripGetSummaryResponse

        def start: (
          key: String,
          asset_id: String,
          ?cluster: Nextbillionai::Models::Skynet::TripStartParams::cluster,
          ?attributes: top,
          ?custom_id: String,
          ?description: String,
          ?meta_data: top,
          ?name: String,
          ?stops: ::Array[Nextbillionai::Skynet::TripStartParams::Stop],
          ?request_options: Nextbillionai::request_opts
        ) -> Nextbillionai::Models::Skynet::TripStartResponse

        def initialize: (client: Nextbillionai::Client) -> void
      end
    end
  end
end
