module Nextbillionai
  module Resources
    class Multigeocode
      class Place
        def create: (
          key: String,
          place: ::Array[Nextbillionai::Multigeocode::PlaceCreateParams::Place],
          ?data_source: Nextbillionai::Multigeocode::PlaceCreateParams::DataSource,
          ?force: bool,
          ?score: Integer,
          ?request_options: Nextbillionai::request_opts
        ) -> Nextbillionai::Models::Multigeocode::PlaceCreateResponse

        def retrieve: (
          String doc_id,
          key: String,
          ?request_options: Nextbillionai::request_opts
        ) -> Nextbillionai::Models::Multigeocode::PlaceRetrieveResponse

        def update: (
          String doc_id,
          key: String,
          ?data_source: Nextbillionai::Multigeocode::PlaceUpdateParams::DataSource,
          ?place: ::Array[Nextbillionai::Multigeocode::PlaceItem],
          ?score: Integer,
          ?request_options: Nextbillionai::request_opts
        ) -> Nextbillionai::Models::Multigeocode::PlaceUpdateResponse

        def delete: (
          String doc_id,
          key: String,
          ?request_options: Nextbillionai::request_opts
        ) -> Nextbillionai::Models::Multigeocode::PlaceDeleteResponse

        def initialize: (client: Nextbillionai::Client) -> void
      end
    end
  end
end
