module Nextbillionai
  module Models
    module Skynet
      type monitor_retrieve_response =
        {
          data: Nextbillionai::Models::Skynet::MonitorRetrieveResponse::Data,
          message: String,
          status: String
        }

      class MonitorRetrieveResponse < Nextbillionai::Internal::Type::BaseModel
        attr_reader data: Nextbillionai::Models::Skynet::MonitorRetrieveResponse::Data?

        def data=: (
          Nextbillionai::Models::Skynet::MonitorRetrieveResponse::Data
        ) -> Nextbillionai::Models::Skynet::MonitorRetrieveResponse::Data

        attr_reader message: String?

        def message=: (String) -> String

        attr_reader status: String?

        def status=: (String) -> String

        def initialize: (
          ?data: Nextbillionai::Models::Skynet::MonitorRetrieveResponse::Data,
          ?message: String,
          ?status: String
        ) -> void

        def to_hash: -> {
          data: Nextbillionai::Models::Skynet::MonitorRetrieveResponse::Data,
          message: String,
          status: String
        }

        type data = { monitor: Nextbillionai::Skynet::SkynetMonitor }

        class Data < Nextbillionai::Internal::Type::BaseModel
          attr_reader monitor: Nextbillionai::Skynet::SkynetMonitor?

          def monitor=: (
            Nextbillionai::Skynet::SkynetMonitor
          ) -> Nextbillionai::Skynet::SkynetMonitor

          def initialize: (
            ?monitor: Nextbillionai::Skynet::SkynetMonitor
          ) -> void

          def to_hash: -> { monitor: Nextbillionai::Skynet::SkynetMonitor }
        end
      end
    end
  end
end
