module Nextbillionai
  module Models
    module Skynet
      type namespaced_apikey_delete_response = { msg: String, status: Integer }

      class NamespacedApikeyDeleteResponse < Nextbillionai::Internal::Type::BaseModel
        attr_reader msg: String?

        def msg=: (String) -> String

        attr_reader status: Integer?

        def status=: (Integer) -> Integer

        def initialize: (?msg: String, ?status: Integer) -> void

        def to_hash: -> { msg: String, status: Integer }
      end
    end
  end
end
