module Nextbillionai
  module Models
    module Skynet
      type pagination =
        { hasmore: bool, page: Integer, size: Integer, total: Integer }

      class Pagination < Nextbillionai::Internal::Type::BaseModel
        attr_reader hasmore: bool?

        def hasmore=: (bool) -> bool

        attr_reader page: Integer?

        def page=: (Integer) -> Integer

        attr_reader size: Integer?

        def size=: (Integer) -> Integer

        attr_reader total: Integer?

        def total=: (Integer) -> Integer

        def initialize: (
          ?hasmore: bool,
          ?page: Integer,
          ?size: Integer,
          ?total: Integer
        ) -> void

        def to_hash: -> {
          hasmore: bool,
          page: Integer,
          size: Integer,
          total: Integer
        }
      end
    end
  end
end
