module Nextbillionai
  module Models
    module Skynet
      type simple_resp = { message: String, status: String }

      class SimpleResp < Nextbillionai::Internal::Type::BaseModel
        attr_reader message: String?

        def message=: (String) -> String

        attr_reader status: String?

        def status=: (String) -> String

        def initialize: (?message: String, ?status: String) -> void

        def to_hash: -> { message: String, status: String }
      end
    end
  end
end
