module Nextbillionai
  module Models
    module Skynet
      type trip_get_summary_response =
        {
          data: Nextbillionai::Models::Skynet::TripGetSummaryResponse::Data,
          message: String,
          status: String
        }

      class TripGetSummaryResponse < Nextbillionai::Internal::Type::BaseModel
        attr_reader data: Nextbillionai::Models::Skynet::TripGetSummaryResponse::Data?

        def data=: (
          Nextbillionai::Models::Skynet::TripGetSummaryResponse::Data
        ) -> Nextbillionai::Models::Skynet::TripGetSummaryResponse::Data

        attr_reader message: String?

        def message=: (String) -> String

        attr_reader status: String?

        def status=: (String) -> String

        def initialize: (
          ?data: Nextbillionai::Models::Skynet::TripGetSummaryResponse::Data,
          ?message: String,
          ?status: String
        ) -> void

        def to_hash: -> {
          data: Nextbillionai::Models::Skynet::TripGetSummaryResponse::Data,
          message: String,
          status: String
        }

        type data =
          {
            trip: Nextbillionai::Models::Skynet::TripGetSummaryResponse::Data::Trip
          }

        class Data < Nextbillionai::Internal::Type::BaseModel
          attr_reader trip: Nextbillionai::Models::Skynet::TripGetSummaryResponse::Data::Trip?

          def trip=: (
            Nextbillionai::Models::Skynet::TripGetSummaryResponse::Data::Trip
          ) -> Nextbillionai::Models::Skynet::TripGetSummaryResponse::Data::Trip

          def initialize: (
            ?trip: Nextbillionai::Models::Skynet::TripGetSummaryResponse::Data::Trip
          ) -> void

          def to_hash: -> {
            trip: Nextbillionai::Models::Skynet::TripGetSummaryResponse::Data::Trip
          }

          type trip =
            {
              id: String,
              asset: Nextbillionai::Skynet::AssetDetails,
              asset_id: String,
              attributes: top,
              created_at: Integer,
              description: String,
              distance: Float,
              duration: Float,
              ended_at: Integer,
              geometry: ::Array[String],
              meta_data: top,
              name: String,
              route: ::Array[Nextbillionai::Skynet::Asset::TrackLocation],
              started_at: Integer,
              state: String,
              stops: ::Array[Nextbillionai::Skynet::TripStop],
              updated_at: Integer
            }

          class Trip < Nextbillionai::Internal::Type::BaseModel
            attr_reader id: String?

            def id=: (String) -> String

            attr_reader asset: Nextbillionai::Skynet::AssetDetails?

            def asset=: (
              Nextbillionai::Skynet::AssetDetails
            ) -> Nextbillionai::Skynet::AssetDetails

            attr_reader asset_id: String?

            def asset_id=: (String) -> String

            attr_reader attributes: top?

            def attributes=: (top) -> top

            attr_reader created_at: Integer?

            def created_at=: (Integer) -> Integer

            attr_reader description: String?

            def description=: (String) -> String

            attr_reader distance: Float?

            def distance=: (Float) -> Float

            attr_reader duration: Float?

            def duration=: (Float) -> Float

            attr_reader ended_at: Integer?

            def ended_at=: (Integer) -> Integer

            attr_reader geometry: ::Array[String]?

            def geometry=: (::Array[String]) -> ::Array[String]

            attr_reader meta_data: top?

            def meta_data=: (top) -> top

            attr_reader name: String?

            def name=: (String) -> String

            attr_reader route: ::Array[Nextbillionai::Skynet::Asset::TrackLocation]?

            def route=: (
              ::Array[Nextbillionai::Skynet::Asset::TrackLocation]
            ) -> ::Array[Nextbillionai::Skynet::Asset::TrackLocation]

            attr_reader started_at: Integer?

            def started_at=: (Integer) -> Integer

            attr_reader state: String?

            def state=: (String) -> String

            attr_reader stops: ::Array[Nextbillionai::Skynet::TripStop]?

            def stops=: (
              ::Array[Nextbillionai::Skynet::TripStop]
            ) -> ::Array[Nextbillionai::Skynet::TripStop]

            attr_reader updated_at: Integer?

            def updated_at=: (Integer) -> Integer

            def initialize: (
              ?id: String,
              ?asset: Nextbillionai::Skynet::AssetDetails,
              ?asset_id: String,
              ?attributes: top,
              ?created_at: Integer,
              ?description: String,
              ?distance: Float,
              ?duration: Float,
              ?ended_at: Integer,
              ?geometry: ::Array[String],
              ?meta_data: top,
              ?name: String,
              ?route: ::Array[Nextbillionai::Skynet::Asset::TrackLocation],
              ?started_at: Integer,
              ?state: String,
              ?stops: ::Array[Nextbillionai::Skynet::TripStop],
              ?updated_at: Integer
            ) -> void

            def to_hash: -> {
              id: String,
              asset: Nextbillionai::Skynet::AssetDetails,
              asset_id: String,
              attributes: top,
              created_at: Integer,
              description: String,
              distance: Float,
              duration: Float,
              ended_at: Integer,
              geometry: ::Array[String],
              meta_data: top,
              name: String,
              route: ::Array[Nextbillionai::Skynet::Asset::TrackLocation],
              started_at: Integer,
              state: String,
              stops: ::Array[Nextbillionai::Skynet::TripStop],
              updated_at: Integer
            }
          end
        end
      end
    end
  end
end
