module Nextbillionai
  module Models
    module Skynet
      type trip_stop = { geofence_id: String, meta_data: top, name: String }

      class TripStop < Nextbillionai::Internal::Type::BaseModel
        attr_reader geofence_id: String?

        def geofence_id=: (String) -> String

        attr_reader meta_data: top?

        def meta_data=: (top) -> top

        attr_reader name: String?

        def name=: (String) -> String

        def initialize: (
          ?geofence_id: String,
          ?meta_data: top,
          ?name: String
        ) -> void

        def to_hash: -> { geofence_id: String, meta_data: top, name: String }
      end
    end
  end
end
