module NextbillionSDK
  module Resources
    class DistanceMatrix
      class Json
        def create: (?request_options: NextbillionSDK::request_opts) -> nil

        def retrieve: (
          destinations: String,
          key: String,
          origins: String,
          ?approaches: NextbillionSDK::Models::DistanceMatrix::JsonRetrieveParams::approaches,
          ?avoid: NextbillionSDK::Models::DistanceMatrix::JsonRetrieveParams::avoid,
          ?bearings: String,
          ?mode: NextbillionSDK::Models::DistanceMatrix::JsonRetrieveParams::mode,
          ?route_failed_prompt: bool,
          ?request_options: NextbillionSDK::request_opts
        ) -> NextbillionSDK::Models::DistanceMatrix::JsonRetrieveResponse

        def initialize: (client: NextbillionSDK::Client) -> void
      end
    end
  end
end
