module NextbillionSDK
  module Resources
    class Skynet
      class Search
        class Polygon
          def create: (
            key: String,
            polygon: NextbillionSDK::Skynet::Search::PolygonCreateParams::Polygon,
            ?filter: String,
            ?match_filter: NextbillionSDK::Skynet::Search::PolygonCreateParams::MatchFilter,
            ?max_search_limit: bool,
            ?pn: Integer,
            ?ps: Integer,
            ?sort: NextbillionSDK::Skynet::Search::PolygonCreateParams::Sort,
            ?request_options: NextbillionSDK::request_opts
          ) -> NextbillionSDK::Skynet::SearchResponse

          def get: (
            key: String,
            polygon: String,
            ?filter: String,
            ?include_all_of_attributes: String,
            ?include_any_of_attributes: String,
            ?max_search_limit: bool,
            ?pn: Integer,
            ?ps: Integer,
            ?sort_by: NextbillionSDK::Models::Skynet::Search::PolygonGetParams::sort_by,
            ?sort_destination: String,
            ?sort_driving_mode: NextbillionSDK::Models::Skynet::Search::PolygonGetParams::sort_driving_mode,
            ?request_options: NextbillionSDK::request_opts
          ) -> NextbillionSDK::Skynet::SearchResponse

          def initialize: (client: NextbillionSDK::Client) -> void
        end
      end
    end
  end
end
