module Nextbillionai
  module Resources
    class Areas
      def list: (
        key: String,
        ?request_options: Nextbillionai::request_opts
      ) -> Nextbillionai::Models::area_list_response

      def initialize: (client: Nextbillionai::Client) -> void
    end
  end
end
