module Nextbillionai
  module Resources
    class Batch
      def create: (
        key: String,
        ?requests: ::Array[Nextbillionai::BatchCreateParams::Request],
        ?request_options: Nextbillionai::request_opts
      ) -> Nextbillionai::Models::BatchCreateResponse

      def retrieve: (
        key: String,
        track_id: String,
        ?request_options: Nextbillionai::request_opts
      ) -> Nextbillionai::Models::BatchRetrieveResponse

      def initialize: (client: Nextbillionai::Client) -> void
    end
  end
end
