module Nextbillionai
  module Resources
    class Browse
      def search: (
        key: String,
        ?at: String,
        ?categories: String,
        ?in_: String,
        ?lang: String,
        ?limit: Integer,
        ?request_options: Nextbillionai::request_opts
      ) -> Nextbillionai::Models::BrowseSearchResponse

      def initialize: (client: Nextbillionai::Client) -> void
    end
  end
end
