module Nextbillionai
  module Resources
    class Directions
      def compute_route: (
        destination: String,
        origin: String,
        ?altcount: Integer,
        ?alternatives: bool,
        ?approaches: String,
        ?avoid: Nextbillionai::Models::DirectionComputeRouteParams::avoid,
        ?bearings: String,
        ?cross_border: bool,
        ?departure_time: Integer,
        ?drive_time_limits: String,
        ?emission_class: Nextbillionai::Models::DirectionComputeRouteParams::emission_class,
        ?exclude: Nextbillionai::Models::DirectionComputeRouteParams::exclude,
        ?geometry: Nextbillionai::Models::DirectionComputeRouteParams::geometry,
        ?hazmat_type: Nextbillionai::Models::DirectionComputeRouteParams::hazmat_type,
        ?mode: Nextbillionai::Models::DirectionComputeRouteParams::mode,
        ?option: Nextbillionai::Models::DirectionComputeRouteParams::option,
        ?overview: Nextbillionai::Models::DirectionComputeRouteParams::overview,
        ?rest_times: String,
        ?road_info: Nextbillionai::Models::DirectionComputeRouteParams::road_info,
        ?route_type: Nextbillionai::Models::DirectionComputeRouteParams::route_type,
        ?steps: bool,
        ?truck_axle_load: Float,
        ?truck_size: String,
        ?truck_weight: Integer,
        ?turn_angle_range: Integer,
        ?waypoints: String,
        ?request_options: Nextbillionai::request_opts
      ) -> Nextbillionai::Models::DirectionComputeRouteResponse

      def initialize: (client: Nextbillionai::Client) -> void
    end
  end
end
