module Nextbillionai
  module Resources
    class Geofence
      attr_reader console: Nextbillionai::Resources::Geofence::Console

      attr_reader batch: Nextbillionai::Resources::Geofence::Batch

      def create: (
        key: String,
        type: Nextbillionai::Models::GeofenceEntityCreate::type_,
        ?circle: Nextbillionai::GeofenceEntityCreate::Circle,
        ?custom_id: String,
        ?isochrone: Nextbillionai::GeofenceEntityCreate::Isochrone,
        ?meta_data: top,
        ?name: String,
        ?polygon: Nextbillionai::GeofenceEntityCreate::Polygon,
        ?tags: ::Array[String],
        ?request_options: Nextbillionai::request_opts
      ) -> Nextbillionai::Models::GeofenceCreateResponse

      def retrieve: (
        String id,
        key: String,
        ?request_options: Nextbillionai::request_opts
      ) -> Nextbillionai::Models::GeofenceRetrieveResponse

      def update: (
        String id,
        key: String,
        ?circle: Nextbillionai::GeofenceUpdateParams::Circle,
        ?isochrone: Nextbillionai::GeofenceUpdateParams::Isochrone,
        ?meta_data: top,
        ?name: String,
        ?polygon: Nextbillionai::GeofenceUpdateParams::Polygon,
        ?tags: ::Array[String],
        ?type: Nextbillionai::Models::GeofenceUpdateParams::type_,
        ?request_options: Nextbillionai::request_opts
      ) -> Nextbillionai::Skynet::SimpleResp

      def list: (
        key: String,
        ?pn: Integer,
        ?ps: Integer,
        ?tags: String,
        ?request_options: Nextbillionai::request_opts
      ) -> Nextbillionai::Models::GeofenceListResponse

      def delete: (
        String id,
        key: String,
        ?request_options: Nextbillionai::request_opts
      ) -> Nextbillionai::Skynet::SimpleResp

      def contains: (
        key: String,
        locations: String,
        ?geofences: String,
        ?verbose: String,
        ?request_options: Nextbillionai::request_opts
      ) -> Nextbillionai::Models::GeofenceContainsResponse

      def initialize: (client: Nextbillionai::Client) -> void
    end
  end
end
