module Nextbillionai
  module Resources
    class Lookup
      def by_id: (
        id: String,
        key: String,
        ?request_options: Nextbillionai::request_opts
      ) -> Nextbillionai::Models::LookupByIDResponse

      def initialize: (client: Nextbillionai::Client) -> void
    end
  end
end
