module Nextbillionai
  module Resources
    class Mdm
      def create_distance_matrix: (
        key: String,
        option: Nextbillionai::Models::MdmCreateDistanceMatrixParams::option,
        origins: String,
        ?spliter: Nextbillionai::Models::MdmCreateDistanceMatrixParams::spliter,
        ?area: Nextbillionai::Models::MdmCreateDistanceMatrixParams::area,
        ?avoid: Nextbillionai::Models::MdmCreateDistanceMatrixParams::avoid,
        ?cross_border: bool,
        ?departure_time: Integer,
        ?destinations: String,
        ?destinations_approach: Nextbillionai::Models::MdmCreateDistanceMatrixParams::destinations_approach,
        ?hazmat_type: Nextbillionai::Models::MdmCreateDistanceMatrixParams::hazmat_type,
        ?mode: Nextbillionai::Models::MdmCreateDistanceMatrixParams::mode,
        ?origins_approach: Nextbillionai::Models::MdmCreateDistanceMatrixParams::origins_approach,
        ?route_type: Nextbillionai::Models::MdmCreateDistanceMatrixParams::route_type,
        ?truck_axle_load: Float,
        ?truck_size: String,
        ?truck_weight: Integer,
        ?request_options: Nextbillionai::request_opts
      ) -> Nextbillionai::Models::MdmCreateDistanceMatrixResponse

      def get_distance_matrix_status: (
        id: String,
        key: String,
        ?request_options: Nextbillionai::request_opts
      ) -> Nextbillionai::Models::MdmGetDistanceMatrixStatusResponse

      def initialize: (client: Nextbillionai::Client) -> void
    end
  end
end
