module Nextbillionai
  module Resources
    class Postalcode
      def retrieve_coordinates: (
        key: String,
        ?at: Nextbillionai::PostalcodeRetrieveCoordinatesParams::At,
        ?country: String,
        ?format_: Nextbillionai::Models::PostalcodeRetrieveCoordinatesParams::format_,
        ?postalcode: String,
        ?request_options: Nextbillionai::request_opts
      ) -> Nextbillionai::Models::PostalcodeRetrieveCoordinatesResponse

      def initialize: (client: Nextbillionai::Client) -> void
    end
  end
end
