module Nextbillionai
  module Resources
    class Revgeocode
      def retrieve: (
        at: String,
        key: String,
        ?in_: String,
        ?lang: String,
        ?request_options: Nextbillionai::request_opts
      ) -> Nextbillionai::Models::RevgeocodeRetrieveResponse

      def initialize: (client: Nextbillionai::Client) -> void
    end
  end
end
