module Nextbillionai
  module Resources
    class Skynet
      attr_reader asset: Nextbillionai::Resources::Skynet::Asset

      attr_reader monitor: Nextbillionai::Resources::Skynet::Monitor

      attr_reader trip: Nextbillionai::Resources::Skynet::Trip

      attr_reader namespaced_apikeys: Nextbillionai::Resources::Skynet::NamespacedApikeys

      attr_reader config: Nextbillionai::Resources::Skynet::Config

      attr_reader search: Nextbillionai::Resources::Skynet::Search

      def subscribe: (
        action: Nextbillionai::Models::SkynetSubscribeParams::action,
        ?id: String,
        ?params: Nextbillionai::SkynetSubscribeParams::Params,
        ?request_options: Nextbillionai::request_opts
      ) -> Nextbillionai::Models::SkynetSubscribeResponse

      def initialize: (client: Nextbillionai::Client) -> void
    end
  end
end
