module Nextbillionai
  module Resources
    class SnapToRoads
      def snap: (
        key: String,
        path: String,
        ?approaches: Nextbillionai::Models::SnapToRoadSnapParams::approaches,
        ?avoid: Nextbillionai::Models::SnapToRoadSnapParams::avoid,
        ?geometry: Nextbillionai::Models::SnapToRoadSnapParams::geometry,
        ?mode: Nextbillionai::Models::SnapToRoadSnapParams::mode,
        ?option: Nextbillionai::Models::SnapToRoadSnapParams::option,
        ?radiuses: String,
        ?road_info: Nextbillionai::Models::SnapToRoadSnapParams::road_info,
        ?timestamps: String,
        ?tolerate_outlier: bool,
        ?request_options: Nextbillionai::request_opts
      ) -> Nextbillionai::Models::SnapToRoadSnapResponse

      def initialize: (client: Nextbillionai::Client) -> void
    end
  end
end
