module Nextbillionai
  module Models
    module Multigeocode
      type place_create_response = { doc_id: String }

      class PlaceCreateResponse < Nextbillionai::Internal::Type::BaseModel
        attr_reader doc_id: String?

        def doc_id=: (String) -> String

        def initialize: (?doc_id: String) -> void

        def to_hash: -> { doc_id: String }
      end
    end
  end
end
