module NextbillionSDK
  module Models
    module Multigeocode
      type place_update_response = { msg: String, status: String }

      class PlaceUpdateResponse < NextbillionSDK::Internal::Type::BaseModel
        attr_reader msg: String?

        def msg=: (String) -> String

        attr_reader status: String?

        def status=: (String) -> String

        def initialize: (?msg: String, ?status: String) -> void

        def to_hash: -> { msg: String, status: String }
      end
    end
  end
end
